import { BlockDef } from '../../registries/BlockRegistry';
import { BlockType } from '../../constants/BlockType';

export const CORE_BLOCKS: BlockDef[] = [
    {
        id: 'village_bell',
        name: 'Village Bell',
        type: BlockType.VILLAGE_BELL,
        color: { r: 255, g: 215, b: 0 },
    },
    {
        id: 'copper_bell',
        name: 'Copper Bell',
        type: BlockType.COPPER_BELL,
        color: { r: 184, g: 115, b: 51 },
    },
    {
        id: 'iron_bell',
        name: 'Iron Bell',
        type: BlockType.IRON_BELL,
        color: { r: 169, g: 169, b: 169 },
    },
    {
        id: 'green_bell',
        name: 'Green Bell',
        type: BlockType.GREEN_BELL,
        color: { r: 46, g: 139, b: 87 },
    },
    {
        id: 'red_bell',
        name: 'Red Bell',
        type: BlockType.RED_BELL,
        color: { r: 178, g: 34, b: 34 },
    },
    {
        id: 'mithril_bell',
        name: 'Mithril Bell',
        type: BlockType.MITHRIL_BELL,
        color: { r: 192, g: 192, b: 255 },
    },
    {
        id: 'black_bell',
        name: 'Black Bell',
        type: BlockType.BLACK_BELL,
        color: { r: 20, g: 20, b: 30 },
    },
    {
        id: 'alchemy_table',
        name: 'Alchemy Table',
        type: BlockType.ALCHEMY_TABLE,
        color: { r: 75, g: 0, b: 130 },
    },
    {
        id: 'slime_puddle',
        name: 'Slime Puddle',
        type: BlockType.SLIME_PUDDLE,
        isIndestructible: true,
        color: { r: 50, g: 205, b: 50 },
    },
    {
        id: 'spider_web',
        name: 'Spider Web',
        type: BlockType.SPIDER_WEB,
        color: { r: 220, g: 220, b: 220 },
    },
    {
        id: 'demon_portal',
        name: 'Demon Portal',
        type: BlockType.DEMON_PORTAL,
        isIndestructible: true,
        color: { r: 139, g: 0, b: 0 },
    },
    {
        id: 'air',
        name: 'Air',
        type: BlockType.AIR,
        isSolid: false,
        isIndestructible: true,
    },
    {
        id: 'grass',
        name: 'Grass',
        type: BlockType.GRASS,
        color: { r: 34, g: 139, b: 34 },
    },
    {
        id: 'dirt',
        name: 'Dirt',
        type: BlockType.DIRT,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'stone',
        name: 'Stone',
        type: BlockType.STONE,
        color: { r: 128, g: 128, b: 128 },
    },
    {
        id: 'water',
        name: 'Water',
        type: BlockType.WATER,
        isSolid: false,
        isIndestructible: true,
        color: { r: 65, g: 105, b: 225 },
    },
    {
        id: 'wood_wall',
        name: 'Wood Wall',
        type: BlockType.WOOD_WALL,
        color: { r: 101, g: 67, b: 33 },
    },
    {
        id: 'wood_floor',
        name: 'Wood Floor',
        type: BlockType.WOOD_FLOOR,
        color: { r: 139, g: 90, b: 43 },
    },
    {
        id: 'door_closed',
        name: 'Door Closed',
        type: BlockType.DOOR_CLOSED,
        color: { r: 160, g: 82, b: 45 },
    },
    {
        id: 'door_open',
        name: 'Door Open',
        type: BlockType.DOOR_OPEN,
        isSolid: false,
        color: { r: 160, g: 82, b: 45 },
    },
    {
        id: 'chest',
        name: 'Chest',
        type: BlockType.CHEST,
        color: { r: 218, g: 165, b: 32 },
    },
    {
        id: 'bed',
        name: 'Bed',
        type: BlockType.BED,
        color: { r: 178, g: 34, b: 34 },
    },
    {
        id: 'dummy',
        name: 'Dummy',
        type: BlockType.DUMMY,
        color: { r: 210, g: 180, b: 140 },
    },
    {
        id: 'trunk',
        name: 'Trunk',
        type: BlockType.TRUNK,
        hardness: 100,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'leaves',
        name: 'Leaves',
        type: BlockType.LEAVES,
        color: { r: 0, g: 100, b: 0 },
    },
    {
        id: 'bush',
        name: 'Bush',
        type: BlockType.BUSH,
        color: { r: 46, g: 139, b: 87 },
    },
    {
        id: 'pine_leaves',
        name: 'Pine Leaves',
        type: BlockType.PINE_LEAVES,
        color: { r: 34, g: 75, b: 42 },
    },
    {
        id: 'dirt_path',
        name: 'Dirt Path',
        type: BlockType.DIRT_PATH,
        color: { r: 180, g: 130, b: 80 },
    },
    {
        id: 'bee_hive',
        name: 'Bee Hive',
        type: BlockType.BEE_HIVE,
        color: { r: 230, g: 180, b: 50 },
    },
    {
        id: 'goblin_camp',
        name: 'Goblin Camp',
        type: BlockType.GOBLIN_CAMP,
        color: { r: 100, g: 50, b: 20 },
    },
    {
        id: 'tent',
        name: 'Tent',
        type: BlockType.TENT,
        color: { r: 100, g: 50, b: 20 },
    },
    {
        id: 'torch',
        name: 'Torch',
        type: BlockType.TORCH,
        isSolid: false,
        hardness: 5,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'mushroom_stem',
        name: 'Mushroom Stem',
        type: BlockType.MUSHROOM_STEM,
        hardness: 20,
        color: { r: 220, g: 220, b: 240 },
    },
    {
        id: 'mushroom_cap',
        name: 'Mushroom Cap',
        type: BlockType.MUSHROOM_CAP,
        hardness: 20,
        color: { r: 0, g: 255, b: 255 },
    },
    {
        id: 'lava',
        name: 'Lava',
        type: BlockType.LAVA,
        isSolid: false,
        isIndestructible: true,
        color: { r: 255, g: 69, b: 0 },
    },
    {
        id: 'crystal',
        name: 'Crystal',
        type: BlockType.CRYSTAL,
        hardness: 80,
        color: { r: 186, g: 85, b: 211 },
    },
    {
        id: 'pot',
        name: 'Pot',
        type: BlockType.POT,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'gravestone',
        name: 'Gravestone',
        type: BlockType.GRAVESTONE,
        color: { r: 105, g: 105, b: 105 },
    },
    {
        id: 'bone_pile_spawner',
        name: 'Bone Pile Spawner',
        type: BlockType.BONE_PILE_SPAWNER,
        isSolid: false,
        color: { r: 240, g: 240, b: 230 },
    },
    {
        id: 'copper_ore',
        name: 'Copper Ore',
        type: BlockType.COPPER_ORE,
        color: { r: 184, g: 115, b: 51 },
    },
    {
        id: 'iron_ore',
        name: 'Iron Ore',
        type: BlockType.IRON_ORE,
        color: { r: 161, g: 157, b: 148 },
    },
    {
        id: 'green_metal_ore',
        name: 'Green Metal Ore',
        type: BlockType.GREEN_METAL_ORE,
        color: { r: 46, g: 139, b: 87 },
    },
    {
        id: 'red_metal_ore',
        name: 'Red Metal Ore',
        type: BlockType.RED_METAL_ORE,
        color: { r: 178, g: 34, b: 34 },
    },
    {
        id: 'mithril_ore',
        name: 'Mithril Ore',
        type: BlockType.MITHRIL_ORE,
        color: { r: 135, g: 206, b: 250 },
    },
    {
        id: 'coal_ore',
        name: 'Coal Ore',
        type: BlockType.COAL_ORE,
        color: { r: 40, g: 40, b: 40 },
    },
    {
        id: 'carpenters_bench',
        name: 'Carpenters Bench',
        type: BlockType.CARPENTERS_BENCH,
        color: { r: 160, g: 100, b: 60 },
    },
    {
        id: 'wooden_staircase',
        name: 'Wooden Staircase',
        type: BlockType.WOODEN_STAIRCASE,
        isSolid: false,
        color: { r: 139, g: 90, b: 43 },
    },
    {
        id: 'masonry_table',
        name: 'Masonry Table',
        type: BlockType.MASONRY_TABLE,
        color: { r: 105, g: 105, b: 105 },
    },
    {
        id: 'shrine',
        name: 'Shrine',
        type: BlockType.SHRINE,
        color: { r: 218, g: 165, b: 32 },
    },
    {
        id: 'furnace',
        name: 'Furnace',
        type: BlockType.FURNACE,
        color: { r: 60, g: 60, b: 60 },
    },
    {
        id: 'orc_tent',
        name: 'Orc Tent',
        type: BlockType.ORC_TENT,
        color: { r: 80, g: 30, b: 30 },
    },
    {
        id: 'wizard_tower_wall',
        name: 'Wizard Tower Wall',
        type: BlockType.WIZARD_TOWER_WALL,
        color: { r: 70, g: 50, b: 120 },
    },
    {
        id: 'wizard_tower_floor',
        name: 'Wizard Tower Floor',
        type: BlockType.WIZARD_TOWER_FLOOR,
        color: { r: 100, g: 80, b: 150 },
    },
    {
        id: 'ice',
        name: 'Ice',
        type: BlockType.ICE,
        color: { r: 173, g: 216, b: 230 },
    },
    {
        id: 'goblin_shaman_tent',
        name: 'Goblin Shaman Tent',
        type: BlockType.GOBLIN_SHAMAN_TENT,
        color: { r: 120, g: 30, b: 120 },
    },
    {
        id: 'ant_hill',
        name: 'Ant Hill',
        type: BlockType.ANT_HILL,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'campfire',
        name: 'Campfire',
        type: BlockType.CAMPFIRE,
        hardness: 5,
        color: { r: 255, g: 140, b: 0 },
    },
    {
        id: 'soil',
        name: 'Soil',
        type: BlockType.SOIL,
        color: { r: 80, g: 50, b: 20 },
    },
    {
        id: 'red_berry_bush',
        name: 'Red Berry Bush',
        type: BlockType.RED_BERRY_BUSH,
        color: { r: 46, g: 139, b: 87 },
    },
    {
        id: 'blue_berry_bush',
        name: 'Blue Berry Bush',
        type: BlockType.BLUE_BERRY_BUSH,
        color: { r: 46, g: 139, b: 87 },
    },
    {
        id: 'black_berry_bush',
        name: 'Black Berry Bush',
        type: BlockType.BLACK_BERRY_BUSH,
        color: { r: 46, g: 139, b: 87 },
    },
    {
        id: 'yellow_berry_bush',
        name: 'Yellow Berry Bush',
        type: BlockType.YELLOW_BERRY_BUSH,
        color: { r: 46, g: 139, b: 87 },
    },
    {
        id: 'seedling_red',
        name: 'Seedling Red',
        type: BlockType.SEEDLING_RED,
        color: { r: 100, g: 180, b: 50 },
    },
    {
        id: 'seedling_blue',
        name: 'Seedling Blue',
        type: BlockType.SEEDLING_BLUE,
        color: { r: 100, g: 180, b: 50 },
    },
    {
        id: 'seedling_black',
        name: 'Seedling Black',
        type: BlockType.SEEDLING_BLACK,
        color: { r: 100, g: 180, b: 50 },
    },
    {
        id: 'seedling_yellow',
        name: 'Seedling Yellow',
        type: BlockType.SEEDLING_YELLOW,
        color: { r: 100, g: 180, b: 50 },
    },
    {
        id: 'anvil',
        name: 'Anvil',
        type: BlockType.ANVIL,
        color: { r: 80, g: 80, b: 80 },
    },
    {
        id: 'spike_floor',
        name: 'Spike Floor',
        type: BlockType.SPIKE_FLOOR,
        isSolid: false,
        color: { r: 120, g: 120, b: 120 },
    },
    {
        id: 'spike_floor_active',
        name: 'Spike Floor Active',
        type: BlockType.SPIKE_FLOOR_ACTIVE,
        isSolid: false,
        color: { r: 120, g: 120, b: 120 },
    },
    {
        id: 'pressure_plate',
        name: 'Pressure Plate',
        type: BlockType.PRESSURE_PLATE,
        isSolid: false,
        color: { r: 150, g: 150, b: 150 },
    },
    {
        id: 'pressure_plate_active',
        name: 'Pressure Plate Active',
        type: BlockType.PRESSURE_PLATE_ACTIVE,
        isSolid: false,
        color: { r: 150, g: 150, b: 150 },
    },
    {
        id: 'lever',
        name: 'Lever',
        type: BlockType.LEVER,
        isSolid: false,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'lever_on',
        name: 'Lever On',
        type: BlockType.LEVER_ON,
        isSolid: false,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'heavy_stone',
        name: 'Heavy Stone',
        type: BlockType.HEAVY_STONE,
        isIndestructible: true,
        color: { r: 60, g: 60, b: 60 },
    },
    {
        id: 'iron_block',
        name: 'Iron Block',
        type: BlockType.IRON_BLOCK,
        color: { r: 180, g: 180, b: 190 },
    },
    {
        id: 'fabric_station',
        name: 'Fabric Station',
        type: BlockType.FABRIC_STATION,
        color: { r: 200, g: 180, b: 160 },
    },
    {
        id: 'leather_station',
        name: 'Leather Station',
        type: BlockType.LEATHER_STATION,
        color: { r: 139, g: 69, b: 19 },
    },
    {
        id: 'marble',
        name: 'Marble',
        type: BlockType.MARBLE,
        color: { r: 240, g: 240, b: 240 },
    },
    {
        id: 'black_marble',
        name: 'Black Marble',
        type: BlockType.BLACK_MARBLE,
        color: { r: 30, g: 30, b: 30 },
    },
    {
        id: 'green_marble',
        name: 'Green Marble',
        type: BlockType.GREEN_MARBLE,
        color: { r: 40, g: 100, b: 60 },
    },
    {
        id: 'obsidian',
        name: 'Obsidian',
        type: BlockType.OBSIDIAN,
        hardness: 200,
        color: { r: 20, g: 10, b: 30 },
    },
    {
        id: 'lava_rock',
        name: 'Lava Rock',
        type: BlockType.LAVA_ROCK,
        color: { r: 80, g: 30, b: 20 },
    },
    {
        id: 'ruby',
        name: 'Ruby',
        type: BlockType.RUBY,
        hardness: 150,
        color: { r: 220, g: 20, b: 60 },
    },
    {
        id: 'emerald',
        name: 'Emerald',
        type: BlockType.EMERALD,
        hardness: 150,
        color: { r: 46, g: 204, b: 113 },
    },
    {
        id: 'black_diamond',
        name: 'Black Diamond',
        type: BlockType.BLACK_DIAMOND,
        hardness: 150,
        color: { r: 10, g: 10, b: 10 },
    },
    {
        id: 'dungeon_brick',
        name: 'Dungeon Brick',
        type: BlockType.DUNGEON_BRICK,
        isIndestructible: true,
        color: { r: 50, g: 50, b: 60 },
    },
    {
        id: 'dungeon_floor',
        name: 'Dungeon Floor',
        type: BlockType.DUNGEON_FLOOR,
        isSolid: false,
        isIndestructible: true,
        color: { r: 70, g: 70, b: 80 },
    },
    {
        id: 'abyssal_gateway',
        name: 'Abyssal Gateway',
        type: BlockType.ABYSSAL_GATEWAY,
        isIndestructible: true,
        color: { r: 100, g: 0, b: 150 },
    },
    {
        id: 'abyssal_brick',
        name: 'Abyssal Brick',
        type: BlockType.ABYSSAL_BRICK,
        isIndestructible: true,
        color: { r: 20, g: 10, b: 20 },
    },
    {
        id: 'abyssal_floor',
        name: 'Abyssal Floor',
        type: BlockType.ABYSSAL_FLOOR,
        isSolid: false,
        isIndestructible: true,
        color: { r: 30, g: 20, b: 30 },
    },
    {
        id: 'stairs_down',
        name: 'Stairs Down',
        type: BlockType.STAIRS_DOWN,
        isSolid: false,
        isIndestructible: true,
        color: { r: 100, g: 100, b: 100 },
    },
    {
        id: 'stairs_up',
        name: 'Stairs Up',
        type: BlockType.STAIRS_UP,
        isSolid: false,
        isIndestructible: true,
        color: { r: 120, g: 120, b: 120 },
    },
    {
        id: 'abyssal_spawner',
        name: 'Abyssal Spawner',
        type: BlockType.ABYSSAL_SPAWNER,
        color: { r: 150, g: 0, b: 50 },
    },
    {
        id: 'conveyor_belt_n',
        name: 'Conveyor Belt N',
        type: BlockType.CONVEYOR_BELT_N,
        isSolid: false,
        color: { r: 80, g: 80, b: 90 },
    },
    {
        id: 'conveyor_belt_s',
        name: 'Conveyor Belt S',
        type: BlockType.CONVEYOR_BELT_S,
        isSolid: false,
        color: { r: 80, g: 80, b: 90 },
    },
    {
        id: 'conveyor_belt_e',
        name: 'Conveyor Belt E',
        type: BlockType.CONVEYOR_BELT_E,
        isSolid: false,
        color: { r: 80, g: 80, b: 90 },
    },
    {
        id: 'conveyor_belt_w',
        name: 'Conveyor Belt W',
        type: BlockType.CONVEYOR_BELT_W,
        isSolid: false,
        color: { r: 80, g: 80, b: 90 },
    },
    {
        id: 'auto_miner',
        name: 'Auto Miner',
        type: BlockType.AUTO_MINER,
        color: { r: 180, g: 100, b: 50 },
    },
    {
        id: 'auto_dropper',
        name: 'Auto Dropper',
        type: BlockType.AUTO_DROPPER,
        color: { r: 150, g: 150, b: 150 },
    },
    {
        id: 'auto_crafter',
        name: 'Auto Crafter',
        type: BlockType.AUTO_CRAFTER,
        color: { r: 100, g: 150, b: 200 },
    },
    {
        id: 'vacuum_hopper',
        name: 'Vacuum Hopper',
        type: BlockType.VACUUM_HOPPER,
        color: { r: 50, g: 150, b: 100 },
    },
    {
        id: 'raeth_gateway',
        name: 'Raeth Gateway',
        type: BlockType.RAETH_GATEWAY,
        isIndestructible: true,
        color: { r: 60, g: 20, b: 100 },
    },
    {
        id: 'voidsight_ore',
        name: 'Voidsight Ore',
        type: BlockType.VOIDSIGHT_ORE,
        hardness: 250,
        color: { r: 0, g: 255, b: 255 }, // Neon blue/cyan
    },
    {
        id: 'slime_trail',
        name: 'Slime Trail',
        type: BlockType.SLIME_TRAIL,
        isSolid: false,
        color: { r: 150, g: 255, b: 50 },
    },
    {
        id: 'observer_spawner',
        name: 'Observer Spawner',
        type: BlockType.OBSERVER_SPAWNER,
        isSolid: false,
        color: { r: 80, g: 0, b: 80 },
    },
    {
        id: 'slug_folk_merchant',
        name: 'Slug Folk Caravan',
        type: BlockType.SLUG_FOLK_MERCHANT,
        isSolid: false,
        color: { r: 100, g: 200, b: 100 },
    },
    {
        id: 'magic_block',
        name: 'Magic Block',
        type: BlockType.MAGIC_BLOCK,
        color: { r: 150, g: 50, b: 250 },
    },
    {
        id: 'dungeon_brick_hard',
        name: 'Dungeon Brick Hard',
        type: BlockType.DUNGEON_BRICK_HARD,
        isIndestructible: true,
        color: { r: 35, g: 35, b: 45 },
    },
    {
        id: 'dungeon_brick_cracked',
        name: 'Dungeon Brick Cracked',
        type: BlockType.DUNGEON_BRICK_CRACKED,
        isIndestructible: true,
        color: { r: 85, g: 85, b: 95 },
    },
    {
        id: 'dungeon_brick_indestructible',
        name: 'Dungeon Brick Indestructible',
        type: BlockType.DUNGEON_BRICK_INDESTRUCTIBLE,
        isIndestructible: true,
        color: { r: 15, g: 15, b: 25 },
    },
    {
        id: 'door_locked',
        name: 'Door Locked',
        type: BlockType.DOOR_LOCKED,
        color: { r: 139, g: 100, b: 20 },
    },
    {
        id: 'door_boss',
        name: 'Door Boss',
        type: BlockType.DOOR_BOSS,
        isIndestructible: true,
        color: { r: 120, g: 0, b: 0 },
    },
    {
        id: 'altar_divine',
        name: 'Altar Divine',
        type: BlockType.ALTAR_DIVINE,
        isIndestructible: true,
        color: { r: 255, g: 255, b: 200 },
    },
    {
        id: 'altar_corrupted',
        name: 'Altar Corrupted',
        type: BlockType.ALTAR_CORRUPTED,
        isIndestructible: true,
        color: { r: 60, g: 0, b: 80 },
    },
    {
        id: 'horde_spawner',
        name: 'Horde Spawner',
        type: BlockType.HORDE_SPAWNER,
        color: { r: 180, g: 0, b: 0 },
    },
    {
        id: 'wall_shooter',
        name: 'Wall Shooter',
        type: BlockType.WALL_SHOOTER,
        color: { r: 100, g: 100, b: 110 },
    },
    {
        id: 'arcane_gate',
        name: 'Arcane Gate',
        type: BlockType.ARCANE_GATE,
        isSolid: false,
        isIndestructible: true,
        color: { r: 138, g: 43, b: 226 },
    },
    {
        id: 'sand',
        name: 'Sand',
        type: BlockType.SAND,
        color: { r: 194, g: 178, b: 128 },
    },
    {
        id: 'clay',
        name: 'Clay',
        type: BlockType.CLAY,
        color: { r: 164, g: 116, b: 73 },
    },
    {
        id: 'mud',
        name: 'Mud',
        type: BlockType.MUD,
        color: { r: 85, g: 57, b: 34 },
    },
    {
        id: 'snow',
        name: 'Snow',
        type: BlockType.SNOW,
        color: { r: 255, g: 250, b: 250 },
    },
    {
        id: 'wood_log',
        name: 'Wood Log',
        type: BlockType.WOOD_LOG,
        color: { r: 120, g: 81, b: 45 },
    },
    {
        id: 'red_sand',
        name: 'Red Sand',
        type: BlockType.RED_SAND,
        color: { r: 204, g: 102, b: 85 },
    },
    {
        id: 'red_clay',
        name: 'Red Clay',
        type: BlockType.RED_CLAY,
        color: { r: 180, g: 60, b: 60 },
    },
    {
        id: 'red_dirt',
        name: 'Red Dirt',
        type: BlockType.RED_DIRT,
        color: { r: 120, g: 40, b: 40 },
    },
    {
        id: 'red_stone',
        name: 'Red Stone',
        type: BlockType.RED_STONE,
        color: { r: 150, g: 80, b: 80 },
    },
    {
        id: 'red_marble',
        name: 'Red Marble',
        type: BlockType.RED_MARBLE,
        color: { r: 200, g: 150, b: 150 },
    },
    {
        id: 'red_wood',
        name: 'Red Wood',
        type: BlockType.RED_WOOD,
        color: { r: 140, g: 50, b: 50 },
    },
    {
        id: 'red_leaves',
        name: 'Red Leaves',
        type: BlockType.RED_LEAVES,
        color: { r: 200, g: 40, b: 40 },
    },
    {
        id: 'black_sand',
        name: 'Black Sand',
        type: BlockType.BLACK_SAND,
        color: { r: 40, g: 40, b: 40 },
    },
    {
        id: 'black_clay',
        name: 'Black Clay',
        type: BlockType.BLACK_CLAY,
        color: { r: 30, g: 30, b: 30 },
    },
    {
        id: 'black_dirt',
        name: 'Black Dirt',
        type: BlockType.BLACK_DIRT,
        color: { r: 20, g: 20, b: 20 },
    },
    {
        id: 'black_stone',
        name: 'Black Stone',
        type: BlockType.BLACK_STONE,
        color: { r: 15, g: 15, b: 15 },
    },
    {
        id: 'black_wood',
        name: 'Black Wood',
        type: BlockType.BLACK_WOOD,
        color: { r: 25, g: 25, b: 25 },
    },
    {
        id: 'black_leaves',
        name: 'Black Leaves',
        type: BlockType.BLACK_LEAVES,
        color: { r: 35, g: 35, b: 35 },
    },
    {
        id: 'green_sand',
        name: 'Green Sand',
        type: BlockType.GREEN_SAND,
        color: { r: 100, g: 160, b: 100 },
    },
    {
        id: 'green_clay',
        name: 'Green Clay',
        type: BlockType.GREEN_CLAY,
        color: { r: 60, g: 120, b: 60 },
    },
    {
        id: 'green_dirt',
        name: 'Green Dirt',
        type: BlockType.GREEN_DIRT,
        color: { r: 40, g: 80, b: 40 },
    },
    {
        id: 'green_stone',
        name: 'Green Stone',
        type: BlockType.GREEN_STONE,
        color: { r: 80, g: 140, b: 80 },
    },
    {
        id: 'green_wood',
        name: 'Green Wood',
        type: BlockType.GREEN_WOOD,
        color: { r: 50, g: 100, b: 50 },
    },
    {
        id: 'green_leaves',
        name: 'Green Leaves',
        type: BlockType.GREEN_LEAVES,
        color: { r: 0, g: 255, b: 0 },
    },
    {
        id: 'blue_sand',
        name: 'Blue Sand',
        type: BlockType.BLUE_SAND,
        color: { r: 100, g: 140, b: 200 },
    },
    {
        id: 'blue_clay',
        name: 'Blue Clay',
        type: BlockType.BLUE_CLAY,
        color: { r: 60, g: 90, b: 160 },
    },
    {
        id: 'blue_dirt',
        name: 'Blue Dirt',
        type: BlockType.BLUE_DIRT,
        color: { r: 40, g: 60, b: 120 },
    },
    {
        id: 'blue_stone',
        name: 'Blue Stone',
        type: BlockType.BLUE_STONE,
        color: { r: 80, g: 100, b: 160 },
    },
    {
        id: 'blue_marble',
        name: 'Blue Marble',
        type: BlockType.BLUE_MARBLE,
        color: { r: 150, g: 180, b: 220 },
    },
    {
        id: 'blue_wood',
        name: 'Blue Wood',
        type: BlockType.BLUE_WOOD,
        color: { r: 50, g: 70, b: 140 },
    },
    {
        id: 'blue_leaves',
        name: 'Blue Leaves',
        type: BlockType.BLUE_LEAVES,
        color: { r: 40, g: 100, b: 220 },
    },
    {
        id: 'orange_sand',
        name: 'Orange Sand',
        type: BlockType.ORANGE_SAND,
        color: { r: 220, g: 150, b: 80 },
    },
    {
        id: 'orange_clay',
        name: 'Orange Clay',
        type: BlockType.ORANGE_CLAY,
        color: { r: 180, g: 100, b: 40 },
    },
    {
        id: 'orange_dirt',
        name: 'Orange Dirt',
        type: BlockType.ORANGE_DIRT,
        color: { r: 140, g: 70, b: 20 },
    },
    {
        id: 'orange_stone',
        name: 'Orange Stone',
        type: BlockType.ORANGE_STONE,
        color: { r: 160, g: 110, b: 70 },
    },
    {
        id: 'orange_marble',
        name: 'Orange Marble',
        type: BlockType.ORANGE_MARBLE,
        color: { r: 220, g: 180, b: 140 },
    },
    {
        id: 'orange_wood',
        name: 'Orange Wood',
        type: BlockType.ORANGE_WOOD,
        color: { r: 160, g: 80, b: 30 },
    },
    {
        id: 'orange_leaves',
        name: 'Orange Leaves',
        type: BlockType.ORANGE_LEAVES,
        color: { r: 240, g: 120, b: 40 },
    },
    {
        id: 'purple_sand',
        name: 'Purple Sand',
        type: BlockType.PURPLE_SAND,
        color: { r: 160, g: 100, b: 200 },
    },
    {
        id: 'purple_clay',
        name: 'Purple Clay',
        type: BlockType.PURPLE_CLAY,
        color: { r: 120, g: 60, b: 160 },
    },
    {
        id: 'purple_dirt',
        name: 'Purple Dirt',
        type: BlockType.PURPLE_DIRT,
        color: { r: 80, g: 40, b: 120 },
    },
    {
        id: 'purple_stone',
        name: 'Purple Stone',
        type: BlockType.PURPLE_STONE,
        color: { r: 120, g: 80, b: 150 },
    },
    {
        id: 'purple_marble',
        name: 'Purple Marble',
        type: BlockType.PURPLE_MARBLE,
        color: { r: 180, g: 150, b: 210 },
    },
    {
        id: 'purple_wood',
        name: 'Purple Wood',
        type: BlockType.PURPLE_WOOD,
        color: { r: 100, g: 50, b: 140 },
    },
    {
        id: 'purple_leaves',
        name: 'Purple Leaves',
        type: BlockType.PURPLE_LEAVES,
        color: { r: 160, g: 60, b: 220 },
    },
    {
        id: 'yellow_sand',
        name: 'Yellow Sand',
        type: BlockType.YELLOW_SAND,
        color: { r: 230, g: 210, b: 100 },
    },
    {
        id: 'yellow_clay',
        name: 'Yellow Clay',
        type: BlockType.YELLOW_CLAY,
        color: { r: 190, g: 170, b: 60 },
    },
    {
        id: 'yellow_dirt',
        name: 'Yellow Dirt',
        type: BlockType.YELLOW_DIRT,
        color: { r: 140, g: 120, b: 30 },
    },
    {
        id: 'yellow_stone',
        name: 'Yellow Stone',
        type: BlockType.YELLOW_STONE,
        color: { r: 180, g: 160, b: 90 },
    },
    {
        id: 'yellow_marble',
        name: 'Yellow Marble',
        type: BlockType.YELLOW_MARBLE,
        color: { r: 240, g: 230, b: 160 },
    },
    {
        id: 'yellow_wood',
        name: 'Yellow Wood',
        type: BlockType.YELLOW_WOOD,
        color: { r: 160, g: 140, b: 40 },
    },
    {
        id: 'yellow_leaves',
        name: 'Yellow Leaves',
        type: BlockType.YELLOW_LEAVES,
        color: { r: 230, g: 220, b: 80 },
    },
    {
        id: 'brown_sand',
        name: 'Brown Sand',
        type: BlockType.BROWN_SAND,
        color: { r: 160, g: 120, b: 80 },
    },
    {
        id: 'brown_clay',
        name: 'Brown Clay',
        type: BlockType.BROWN_CLAY,
        color: { r: 130, g: 90, b: 50 },
    },
    {
        id: 'brown_dirt',
        name: 'Brown Dirt',
        type: BlockType.BROWN_DIRT,
        color: { r: 100, g: 60, b: 30 },
    },
    {
        id: 'brown_stone',
        name: 'Brown Stone',
        type: BlockType.BROWN_STONE,
        color: { r: 120, g: 90, b: 70 },
    },
    {
        id: 'brown_marble',
        name: 'Brown Marble',
        type: BlockType.BROWN_MARBLE,
        color: { r: 170, g: 140, b: 110 },
    },
    {
        id: 'brown_wood',
        name: 'Brown Wood',
        type: BlockType.BROWN_WOOD,
        color: { r: 110, g: 70, b: 40 },
    },
    {
        id: 'brown_leaves',
        name: 'Brown Leaves',
        type: BlockType.BROWN_LEAVES,
        color: { r: 140, g: 100, b: 60 },
    },
    {
        id: 'silver_ore',
        name: 'Silver Ore',
        type: BlockType.SILVER_ORE,
        color: { r: 192, g: 192, b: 192 },
    },
    {
        id: 'gold_ore',
        name: 'Gold Ore',
        type: BlockType.GOLD_ORE,
        color: { r: 255, g: 215, b: 0 },
    },
    {
        id: 'platinum_ore',
        name: 'Platinum Ore',
        type: BlockType.PLATINUM_ORE,
        color: { r: 229, g: 228, b: 226 },
    },
    {
        id: 'adamantium_ore',
        name: 'Adamantium Ore',
        type: BlockType.ADAMANTIUM_ORE,
        color: { r: 119, g: 136, b: 153 },
    },
    {
        id: 'eternium_ore',
        name: 'Eternium Ore',
        type: BlockType.ETERNIUM_ORE,
        color: { r: 216, g: 191, b: 216 },
    },
    {
        id: 'black_metal_ore',
        name: 'Black Metal Ore',
        type: BlockType.BLACK_METAL_ORE,
        color: { r: 40, g: 40, b: 45 },
    },
    {
        id: 'blue_metal_ore',
        name: 'Blue Metal Ore',
        type: BlockType.BLUE_METAL_ORE,
        color: { r: 65, g: 105, b: 225 },
    },
    {
        id: 'orange_metal_ore',
        name: 'Orange Metal Ore',
        type: BlockType.ORANGE_METAL_ORE,
        color: { r: 255, g: 140, b: 0 },
    },
    {
        id: 'purple_metal_ore',
        name: 'Purple Metal Ore',
        type: BlockType.PURPLE_METAL_ORE,
        color: { r: 147, g: 112, b: 219 },
    },
    {
        id: 'yellow_metal_ore',
        name: 'Yellow Metal Ore',
        type: BlockType.YELLOW_METAL_ORE,
        color: { r: 255, g: 255, b: 100 },
    },
    {
        id: 'plutonium_ore',
        name: 'Plutonium Ore',
        type: BlockType.PLUTONIUM_ORE,
        color: { r: 50, g: 205, b: 50 },
    },
    {
        id: 'green_crystal',
        name: 'Green Crystal',
        type: BlockType.GREEN_CRYSTAL,
        color: { r: 50, g: 255, b: 50 },
    },
    {
        id: 'red_crystal',
        name: 'Red Crystal',
        type: BlockType.RED_CRYSTAL,
        color: { r: 255, g: 50, b: 50 },
    },
    {
        id: 'black_crystal',
        name: 'Black Crystal',
        type: BlockType.BLACK_CRYSTAL,
        color: { r: 30, g: 30, b: 30 },
    },
    {
        id: 'blue_crystal',
        name: 'Blue Crystal',
        type: BlockType.BLUE_CRYSTAL,
        color: { r: 50, g: 50, b: 255 },
    },
    {
        id: 'orange_crystal',
        name: 'Orange Crystal',
        type: BlockType.ORANGE_CRYSTAL,
        color: { r: 255, g: 165, b: 0 },
    },
    {
        id: 'purple_crystal',
        name: 'Purple Crystal',
        type: BlockType.PURPLE_CRYSTAL,
        color: { r: 200, g: 50, b: 255 },
    },
    {
        id: 'yellow_crystal',
        name: 'Yellow Crystal',
        type: BlockType.YELLOW_CRYSTAL,
        color: { r: 255, g: 255, b: 50 },
    },
    {
        id: 'green_glow_crystal',
        name: 'Green Glow Crystal',
        type: BlockType.GREEN_GLOW_CRYSTAL,
        color: { r: 100, g: 255, b: 100 },
    },
    {
        id: 'red_glow_crystal',
        name: 'Red Glow Crystal',
        type: BlockType.RED_GLOW_CRYSTAL,
        color: { r: 255, g: 100, b: 100 },
    },
    {
        id: 'blue_glow_crystal',
        name: 'Blue Glow Crystal',
        type: BlockType.BLUE_GLOW_CRYSTAL,
        color: { r: 100, g: 100, b: 255 },
    },
    {
        id: 'orange_glow_crystal',
        name: 'Orange Glow Crystal',
        type: BlockType.ORANGE_GLOW_CRYSTAL,
        color: { r: 255, g: 200, b: 100 },
    },
    {
        id: 'purple_glow_crystal',
        name: 'Purple Glow Crystal',
        type: BlockType.PURPLE_GLOW_CRYSTAL,
        color: { r: 220, g: 100, b: 255 },
    },
    {
        id: 'yellow_glow_crystal',
        name: 'Yellow Glow Crystal',
        type: BlockType.YELLOW_GLOW_CRYSTAL,
        color: { r: 255, g: 255, b: 150 },
    },
    {
        id: 'jade',
        name: 'Jade',
        type: BlockType.JADE,
        color: { r: 0, g: 168, b: 107 },
    },
    {
        id: 'diamond',
        name: 'Diamond',
        type: BlockType.DIAMOND,
        color: { r: 185, g: 242, b: 255 },
    },
    {
        id: 'green_diamond',
        name: 'Green Diamond',
        type: BlockType.GREEN_DIAMOND,
        color: { r: 150, g: 255, b: 150 },
    },
    {
        id: 'purple_diamond',
        name: 'Purple Diamond',
        type: BlockType.PURPLE_DIAMOND,
        color: { r: 200, g: 150, b: 255 },
    },
    {
        id: 'sapphire',
        name: 'Sapphire',
        type: BlockType.SAPPHIRE,
        color: { r: 15, g: 82, b: 186 },
    },
    {
        id: 'amber',
        name: 'Amber',
        type: BlockType.AMBER,
        color: { r: 255, g: 191, b: 0 },
    },
    {
        id: 'green_amber',
        name: 'Green Amber',
        type: BlockType.GREEN_AMBER,
        color: { r: 150, g: 200, b: 50 },
    },
    {
        id: 'red_coal',
        name: 'Red Coal',
        type: BlockType.RED_COAL,
        color: { r: 100, g: 20, b: 20 },
    },
    {
        id: 'black_fire_rock',
        name: 'Black Fire Rock',
        type: BlockType.BLACK_FIRE_ROCK,
        color: { r: 20, g: 10, b: 10 },
    },
    {
        id: 'salt',
        name: 'Salt',
        type: BlockType.SALT,
        color: { r: 240, g: 240, b: 245 },
    },
    {
        id: 'moonstone',
        name: 'Moonstone',
        type: BlockType.MOONSTONE,
        color: { r: 220, g: 240, b: 255 },
    },
    {
        id: 'void_matter',
        name: 'Void Matter',
        type: BlockType.VOID_MATTER,
        color: { r: 10, g: 0, b: 25 },
    },
    {
        id: 'astral_dust',
        name: 'Astral Dust',
        type: BlockType.ASTRAL_DUST,
        color: { r: 180, g: 150, b: 255 },
    },
    {
        id: 'chrono_glass',
        name: 'Chrono Glass',
        type: BlockType.CHRONO_GLASS,
        color: { r: 255, g: 240, b: 180 },
    },
    {
        id: 'frost_wood',
        name: 'Frost Wood',
        type: BlockType.FROST_WOOD,
        color: { r: 180, g: 220, b: 255 },
    },
    {
        id: 'blood_stone',
        name: 'Blood Stone',
        type: BlockType.BLOOD_STONE,
        color: { r: 180, g: 20, b: 40 },
    },
    {
        id: 'sun_rock',
        name: 'Sun Rock',
        type: BlockType.SUN_ROCK,
        color: { r: 255, g: 220, b: 100 },
    },
    {
        id: 'pale_slime_block',
        name: 'Pale Slime Block',
        type: BlockType.PALE_SLIME_BLOCK,
        color: { r: 200, g: 255, b: 180 },
    },
    {
        id: 'coralline_rock',
        name: 'Coralline Rock',
        type: BlockType.CORALLINE_ROCK,
        color: { r: 255, g: 150, b: 140 },
    },
    {
        id: 'echo_stone',
        name: 'Echo Stone',
        type: BlockType.ECHO_STONE,
        color: { r: 160, g: 180, b: 200 },
    },
    {
        id: 'areth_spawner',
        name: 'Areth Spawner',
        type: BlockType.ARETH_SPAWNER,
        color: { r: 150, g: 20, b: 20 },
    },
    {
        id: 'merchant',
        name: 'Merchant',
        type: BlockType.MERCHANT,
        color: { r: 100, g: 100, b: 150 },
    },
    {
        id: 'draconic_merchant',
        name: 'Draconic Merchant',
        type: BlockType.DRACONIC_MERCHANT,
        color: { r: 150, g: 120, b: 50 },
    },
    {
        id: 'kobold_tent',
        name: 'Kobold Tent',
        type: BlockType.KOBOLD_TENT,
        color: { r: 170, g: 120, b: 80 },
    },
    {
        id: 'drake_nest',
        name: 'Drake Nest',
        type: BlockType.DRAKE_NEST,
        color: { r: 130, g: 50, b: 20 },
    },
    {
        id: 'lava_pool',
        name: 'Lava Pool',
        type: BlockType.LAVA_POOL,
        color: { r: 255, g: 80, b: 0 },
    },
    {
        id: 'ancient_wood',
        name: 'Ancient Wood',
        type: BlockType.ANCIENT_WOOD,
        color: { r: 60, g: 45, b: 35 },
    },
    {
        id: 'ancient_leaves',
        name: 'Ancient Leaves',
        type: BlockType.ANCIENT_LEAVES,
        color: { r: 255, g: 255, b: 255 }, // Glowing white leaves
    },
    {
        id: 'glowing_mushroom_block',
        name: 'Glowing Mushroom',
        type: BlockType.GLOWING_MUSHROOM_BLOCK,
        color: { r: 180, g: 0, b: 255 },
    },
    {
        id: 'fairy_spawner',
        name: 'Fairy Spawner',
        type: BlockType.FAIRY_SPAWNER,
        color: { r: 255, g: 100, b: 220 }, // Pink
    },
    {
        id: 'dark_elf_spawner',
        name: 'Dark Elf Spawner',
        type: BlockType.DARK_ELF_SPAWNER,
        color: { r: 80, g: 60, b: 120 }, // Purple/Dark
    },
    {
        id: 'gryphon_nest',
        name: 'Gryphon Nest',
        type: BlockType.GRYPHON_NEST,
        color: { r: 160, g: 150, b: 100 },
    },
    {
        id: 'gnome_spawner',
        name: 'Gnome Spawner',
        type: BlockType.GNOME_SPAWNER,
        color: { r: 100, g: 150, b: 150 }, // Invisible generally, but editor color
    },
    {
        id: 'dwarf_spawner',
        name: 'Dwarf Spawner',
        type: BlockType.DWARF_SPAWNER,
        color: { r: 120, g: 100, b: 80 },
    },
    {
        id: 'rock_golem_spawner',
        name: 'Rock Golem Spawner',
        type: BlockType.ROCK_GOLEM_SPAWNER,
        color: { r: 100, g: 100, b: 100 },
    },
    {
        id: 'mine_shaft_wood',
        name: 'Mine Shaft Wood',
        type: BlockType.MINE_SHAFT_WOOD,
        color: { r: 75, g: 50, b: 35 }, // Dark brown
    },
    {
        id: 'lantern_block',
        name: 'Lantern',
        type: BlockType.LANTERN_BLOCK,
        color: { r: 255, g: 200, b: 50 }, // Bright yellow/glow
    },
    {
        id: 'deep_slate',
        name: 'Deep Slate',
        type: BlockType.DEEP_SLATE,
        color: { r: 45, g: 45, b: 50 }, // Very dark stone
    },
    // Gnomish Wiring & Logic Blocks
    {
        id: 'wire_off',
        name: 'Wire (Off)',
        type: BlockType.WIRE_OFF,
        color: { r: 100, g: 30, b: 30 },
        isSolid: false,
        hardness: 20
    },
    {
        id: 'wire_on',
        name: 'Wire (On)',
        type: BlockType.WIRE_ON,
        color: { r: 255, g: 50, b: 50 },
        isSolid: false,
        hardness: 20
    },
    {
        id: 'piston_closed',
        name: 'Piston (Closed)',
        type: BlockType.PISTON_CLOSED,
        color: { r: 120, g: 120, b: 120 },
        isSolid: true,
        hardness: 100
    },
    {
        id: 'piston_open',
        name: 'Piston (Open)',
        type: BlockType.PISTON_OPEN,
        color: { r: 60, g: 60, b: 60 },
        isSolid: false, // Players can walk through when open
        hardness: 100
    },
    {
        id: 'arrow_turret',
        name: 'Arrow Turret',
        type: BlockType.ARROW_TURRET,
        color: { r: 160, g: 100, b: 40 },
        isSolid: true,
        hardness: 80
    },
    {
        id: 'worker_gnome',
        name: 'Gnome Worker',
        type: BlockType.WORKER_GNOME,
        color: { r: 200, g: 150, b: 100 },
        isSolid: true,
        hardness: 50
    },
    {
        id: 'tilled_soil_dry',
        name: 'Dry Tilled Soil',
        type: BlockType.TILLED_SOIL_DRY,
        color: { r: 105, g: 75, b: 50 } // Lighter brown than dirt
    },
    {
        id: 'tilled_soil_wet',
        name: 'Wet Tilled Soil',
        type: BlockType.TILLED_SOIL_WET,
        color: { r: 75, g: 45, b: 20 } // Dark rich brown
    },
    {
        id: 'crop_stage_1',
        name: 'Seeds',
        type: BlockType.CROP_STAGE_1,
        isSolid: false,
        color: { r: 154, g: 205, b: 50 },
        hardness: 5
    },
    {
        id: 'crop_stage_2',
        name: 'Sprouts',
        type: BlockType.CROP_STAGE_2,
        isSolid: false,
        color: { r: 50, g: 205, b: 50 },
        hardness: 5
    },
    {
        id: 'crop_stage_3',
        name: 'Crops',
        type: BlockType.CROP_STAGE_3,
        isSolid: false,
        color: { r: 34, g: 139, b: 34 },
        hardness: 10
    },
    {
        id: 'archer_mercenary',
        name: 'Archer Mercenary',
        type: BlockType.ARCHER_MERCENARY,
        color: { r: 50, g: 150, b: 50 },
        isSolid: true,
        hardness: 40
    },
    { id: 'goblin_tent_rockhurler', name: 'Goblin Rockhurler Tent', type: BlockType.GOBLIN_TENT_ROCKHURLER, color: { r: 100, g: 120, b: 80 }, isSolid: true, hardness: 60, isIndestructible: true },
    { id: 'goblin_tent_gardener', name: 'Goblin Gardener Tent', type: BlockType.GOBLIN_TENT_GARDENER, color: { r: 80, g: 140, b: 80 }, isSolid: true, hardness: 60, isIndestructible: true },
    { id: 'goblin_tent_boomeranger', name: 'Goblin Boomeranger Tent', type: BlockType.GOBLIN_TENT_BOOMERANGER, color: { r: 120, g: 100, b: 60 }, isSolid: true, hardness: 60, isIndestructible: true },
    { id: 'goblin_tent_alchemist', name: 'Goblin Alchemist Tent', type: BlockType.GOBLIN_TENT_ALCHEMIST, color: { r: 60, g: 80, b: 140 }, isSolid: true, hardness: 60, isIndestructible: true },
    { id: 'goblin_tent_miner', name: 'Goblin Miner Tent', type: BlockType.GOBLIN_TENT_MINER, color: { r: 90, g: 90, b: 100 }, isSolid: true, hardness: 60, isIndestructible: true },
    { id: 'orc_tent_brute', name: 'Orc Brute Tent', type: BlockType.ORC_TENT_BRUTE, color: { r: 140, g: 80, b: 60 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'orc_tent_shaman', name: 'Orc Shaman Tent', type: BlockType.ORC_TENT_SHAMAN, color: { r: 160, g: 60, b: 160 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'orc_tent_hunter', name: 'Orc Hunter Tent', type: BlockType.ORC_TENT_HUNTER, color: { r: 120, g: 140, b: 60 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'kobold_tent_trapper', name: 'Kobold Trapper Tent', type: BlockType.KOBOLD_TENT_TRAPPER, color: { r: 180, g: 140, b: 60 }, isSolid: true, hardness: 50, isIndestructible: true },
    { id: 'kobold_tent_warrior', name: 'Kobold Warrior Tent', type: BlockType.KOBOLD_TENT_WARRIOR, color: { r: 200, g: 60, b: 60 }, isSolid: true, hardness: 50, isIndestructible: true },
    { id: 'kobold_tent_shaman', name: 'Kobold Shaman Tent', type: BlockType.KOBOLD_TENT_SHAMAN, color: { r: 60, g: 100, b: 200 }, isSolid: true, hardness: 50, isIndestructible: true },
    { id: 'kobold_tent_bomber', name: 'Kobold Bomber Tent', type: BlockType.KOBOLD_TENT_BOMBER, color: { r: 250, g: 100, b: 0 }, isSolid: true, hardness: 50, isIndestructible: true },
    { id: 'kobold_tent_dragonkeeper', name: 'Kobold Dragonkeeper Shrine', type: BlockType.KOBOLD_TENT_DRAGONKEEPER, color: { r: 212, g: 175, b: 55 }, isSolid: true, hardness: 50, isIndestructible: true },
    { id: 'dark_elf_tent', name: 'Dark Elf Tent', type: BlockType.DARK_ELF_TENT, color: { r: 60, g: 40, b: 80 }, isSolid: true, hardness: 120, isIndestructible: true },
    { id: 'giant_camp', name: 'Giant Camp', type: BlockType.GIANT_CAMP, color: { r: 80, g: 70, b: 60 }, isSolid: true, hardness: 200, isIndestructible: true },
    { id: 'titan_nest', name: 'Titan Nest', type: BlockType.TITAN_NEST, color: { r: 120, g: 160, b: 80 }, isSolid: true, hardness: 250, isIndestructible: true },
    { id: 'void_beacon', name: 'Void Beacon', type: BlockType.VOID_BEACON, color: { r: 255, g: 0, b: 200 }, isSolid: true, hardness: 500, isIndestructible: false /* the beacon must be destroyed! */ },
    { id: 'poison_water', name: 'Poison Water', type: BlockType.POISON_WATER, color: { r: 128, g: 0, b: 128 }, isSolid: false },
    { id: 'slug_folk_merchant', name: 'Slug Folk Merchant', type: BlockType.SLUG_FOLK_MERCHANT, color: { r: 100, g: 150, b: 100 }, isSolid: true, isIndestructible: true },
    { id: 'weed', name: 'Weed', type: BlockType.WEED, isSolid: false, color: {r: 34, g: 100, b: 34}, hardness: 5 },
    { id: 'dragon_lair', name: 'Dragon Lair', type: BlockType.DRAGON_LAIR, color: {r: 150, g: 40, b:40}, isSolid: true, hardness: 1000, isIndestructible: true },
    { id: 'observer_spawner', name: 'Observer Spawner', type: BlockType.OBSERVER_SPAWNER, color: { r: 150, g: 50, b: 250 }, isSolid: true, isIndestructible: true },
    { id: 'voidsight_ore', name: 'Voidsight Ore', type: BlockType.VOIDSIGHT_ORE, color: { r: 150, g: 0, b: 255 }, isSolid: true, hardness: 200 },
    
    // THE DJINN OF RATHE UPDATE
    { id: 'gargoyle_pedestal', name: 'Gargoyle Pedestal', type: BlockType.GARGOYLE_PEDESTAL, color: { r: 100, g: 100, b: 100 }, isSolid: true, hardness: 200 },
    { id: 'djinn_lamp_shrine', name: 'Djinn Lamp Shrine', type: BlockType.DJINN_LAMP_SHRINE, color: { r: 255, g: 215, b: 0 }, isSolid: true, hardness: 200 },
    
    // NEW METALS UPDATE
    { id: 'silver_ore', name: 'Silver Ore', type: BlockType.SILVER_ORE, color: { r: 192, g: 192, b: 192 }, isSolid: true, hardness: 50 },
    { id: 'gold_ore', name: 'Gold Ore', type: BlockType.GOLD_ORE, color: { r: 255, g: 215, b: 0 }, isSolid: true, hardness: 50 },
    { id: 'platinum_ore', name: 'Platinum Ore', type: BlockType.PLATINUM_ORE, color: { r: 229, g: 228, b: 226 }, isSolid: true, hardness: 50 },
    { id: 'adamantium_ore', name: 'Adamantium Ore', type: BlockType.ADAMANTIUM_ORE, color: { r: 100, g: 149, b: 237 }, isSolid: true, hardness: 50 },
    { id: 'eternium_ore', name: 'Eternium Ore', type: BlockType.ETERNIUM_ORE, color: { r: 255, g: 105, b: 180 }, isSolid: true, hardness: 50 },
    { id: 'black_metal_ore', name: 'Black Metal Ore', type: BlockType.BLACK_METAL_ORE, color: { r: 50, g: 50, b: 50 }, isSolid: true, hardness: 50 },
    { id: 'blue_metal_ore', name: 'Blue Metal Ore', type: BlockType.BLUE_METAL_ORE, color: { r: 0, g: 0, b: 255 }, isSolid: true, hardness: 50 },
    { id: 'orange_metal_ore', name: 'Orange Metal Ore', type: BlockType.ORANGE_METAL_ORE, color: { r: 255, g: 165, b: 0 }, isSolid: true, hardness: 50 },
    { id: 'purple_metal_ore', name: 'Purple Metal Ore', type: BlockType.PURPLE_METAL_ORE, color: { r: 128, g: 0, b: 128 }, isSolid: true, hardness: 50 },
    { id: 'yellow_metal_ore', name: 'Yellow Metal Ore', type: BlockType.YELLOW_METAL_ORE, color: { r: 255, g: 255, b: 0 }, isSolid: true, hardness: 50 },
    { id: 'plUTONIUM_ore', name: 'Plutonium Ore', type: BlockType.PLUTONIUM_ORE, color: { r: 0, g: 255, b: 0 }, isSolid: true, hardness: 50 },
    
    { id: 'silver_block', name: 'Silver Block', type: BlockType.SILVER_BLOCK, color: { r: 192, g: 192, b: 192 }, isSolid: true, hardness: 200 },
    { id: 'gold_block', name: 'Gold Block', type: BlockType.GOLD_BLOCK, color: { r: 255, g: 215, b: 0 }, isSolid: true, hardness: 200 },
    { id: 'platinum_block', name: 'Platinum Block', type: BlockType.PLATINUM_BLOCK, color: { r: 229, g: 228, b: 226 }, isSolid: true, hardness: 200 },
    { id: 'adamantium_block', name: 'Adamantium Block', type: BlockType.ADAMANTIUM_BLOCK, color: { r: 100, g: 149, b: 237 }, isSolid: true, hardness: 200 },
    { id: 'eternium_block', name: 'Eternium Block', type: BlockType.ETERNIUM_BLOCK, color: { r: 255, g: 105, b: 180 }, isSolid: true, hardness: 200 },
    { id: 'black_metal_block', name: 'Black Metal Block', type: BlockType.BLACK_METAL_BLOCK, color: { r: 50, g: 50, b: 50 }, isSolid: true, hardness: 200 },
    { id: 'blue_metal_block', name: 'Blue Metal Block', type: BlockType.BLUE_METAL_BLOCK, color: { r: 0, g: 0, b: 255 }, isSolid: true, hardness: 200 },
    { id: 'orange_metal_block', name: 'Orange Metal Block', type: BlockType.ORANGE_METAL_BLOCK, color: { r: 255, g: 165, b: 0 }, isSolid: true, hardness: 200 },
    { id: 'purple_metal_block', name: 'Purple Metal Block', type: BlockType.PURPLE_METAL_BLOCK, color: { r: 128, g: 0, b: 128 }, isSolid: true, hardness: 200 },
    { id: 'yellow_metal_block', name: 'Yellow Metal Block', type: BlockType.YELLOW_METAL_BLOCK, color: { r: 255, g: 255, b: 0 }, isSolid: true, hardness: 200 },
    { id: 'plUTONIUM_block', name: 'Plutonium Block', type: BlockType.PLUTONIUM_BLOCK, color: { r: 0, g: 255, b: 0 }, isSolid: true, hardness: 200 },
    { id: 'gremlin_camp', name: 'Gremlin Camp', type: BlockType.GREMLIN_CAMP, color: { r: 60, g: 100, b: 60 }, isSolid: true, hardness: 150 },
    { id: 'sphynx_spawner', name: 'Sphinx Spawner', type: BlockType.SPHINX_SPAWNER, color: { r: 218, g: 165, b: 32 }, isSolid: true, isIndestructible: true },
    { id: 'cooking_pot', name: 'Cooking Pot', type: BlockType.COOKING_POT, color: { r: 60, g: 60, b: 70 }, isSolid: true, hardness: 50 },
    
    // THERA UPDATE
    { id: 'thera_gateway', name: 'Thera Gateway', type: BlockType.THERA_GATEWAY, color: { r: 60, g: 180, b: 60 }, isSolid: true, isIndestructible: true },
    { id: 'tropical_wood', name: 'Tropical Wood', type: BlockType.TROPICAL_WOOD, color: { r: 120, g: 60, b: 20 }, isSolid: true, hardness: 40 },
    { id: 'tropical_leaves', name: 'Tropical Leaves', type: BlockType.TROPICAL_LEAVES, color: { r: 30, g: 150, b: 40 }, isSolid: false, hardness: 10 },
    { id: 'swamp_water', name: 'Swamp Water', type: BlockType.SWAMP_WATER, color: { r: 40, g: 80, b: 40 }, isSolid: false },
    { id: 'fern', name: 'Fern', type: BlockType.FERN, color: { r: 50, g: 200, b: 50 }, isSolid: false, hardness: 5 },
    { id: 'tricera_tent', name: 'Tricera Folk Tent', type: BlockType.TRICERA_TENT, color: { r: 140, g: 160, b: 120 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'raptor_tent', name: 'Raptor Folk Tent', type: BlockType.RAPTOR_TENT, color: { r: 180, g: 100, b: 60 }, isSolid: true, hardness: 80, isIndestructible: true },
    { id: 'frog_tent', name: 'Frog Folk Hut', type: BlockType.FROG_TENT, color: { r: 40, g: 140, b: 100 }, isSolid: true, hardness: 60, isIndestructible: true },
    { id: 'fossil_ore', name: 'Fossil Ore', type: BlockType.FOSSIL_ORE, color: { r: 200, g: 180, b: 150 }, isSolid: true, hardness: 60 },

    // ATHER UPDATE
    { id: 'ather_gateway', name: 'Ather Gateway', type: BlockType.ATHER_GATEWAY, color: { r: 200, g: 50, b: 50 }, isSolid: true, isIndestructible: true },
    { id: 'giant_mushroom_stalk', name: 'Giant Mushroom Stalk', type: BlockType.GIANT_MUSHROOM_STALK, color: { r: 220, g: 210, b: 190 }, isSolid: true, hardness: 30 },
    { id: 'giant_mushroom_cap_red', name: 'Giant Mushroom Cap (Red)', type: BlockType.GIANT_MUSHROOM_CAP_RED, color: { r: 200, g: 40, b: 40 }, isSolid: true, hardness: 20 },
    { id: 'giant_mushroom_cap_brown', name: 'Giant Mushroom Cap (Brown)', type: BlockType.GIANT_MUSHROOM_CAP_BROWN, color: { r: 140, g: 100, b: 60 }, isSolid: true, hardness: 20 },
    { id: 'glowcap_mushroom', name: 'Glowcap Mushroom', type: BlockType.GLOWCAP_MUSHROOM, color: { r: 100, g: 255, b: 200 }, isSolid: false, hardness: 10 },
    { id: 'fungi_folk_tent', name: 'Fungi Folk Hut', type: BlockType.FUNGI_FOLK_TENT, color: { r: 160, g: 80, b: 80 }, isSolid: true, hardness: 60, isIndestructible: true },
    { id: 'ogre_den', name: 'Ogre Den', type: BlockType.OGRE_DEN, color: { r: 80, g: 70, b: 60 }, isSolid: true, hardness: 150, isIndestructible: true },
    { id: 'troll_cave', name: 'Troll Cave', type: BlockType.TROLL_CAVE, color: { r: 60, g: 60, b: 70 }, isSolid: true, hardness: 120, isIndestructible: true },
    { id: 'clay_ore', name: 'Raw Clay Deposit', type: BlockType.CLAY_ORE, color: { r: 180, g: 120, b: 90 }, isSolid: true, hardness: 50 },

    // ARENA UPDATE
    { id: 'blood_altar', name: 'Blood Altar', type: BlockType.BLOOD_ALTAR, color: { r: 180, g: 20, b: 20 }, isSolid: true, isIndestructible: true },
    { id: 'arcane_turret', name: 'Arcane Turret', type: BlockType.ARCANE_TURRET, color: { r: 219, g: 39, b: 119 }, isSolid: true, hardness: 100 },

    // CONTRACTS
    { id: 'gardener_gnome', name: 'Gardener Gnome', type: BlockType.GARDENER_GNOME, color: { r: 100, g: 200, b: 100 }, isSolid: true, hardness: 50 },
    { id: 'guard_mercenary', name: 'Guard Mercenary', type: BlockType.GUARD_MERCENARY, color: { r: 100, g: 100, b: 200 }, isSolid: true, hardness: 100 },
    { id: 'miner_gnome', name: 'Miner Gnome', type: BlockType.MINER_GNOME, color: { r: 150, g: 150, b: 150 }, isSolid: true, hardness: 50 },

    // THE THRAE UPDATE
    { id: 'halfling_house_spawner', name: 'Halfling House', type: BlockType.HALFLING_HOUSE_SPAWNER, color: { r: 180, g: 140, b: 80 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'pit_bull_tent', name: 'Pit Bull Tent', type: BlockType.PIT_BULL_TENT, color: { r: 120, g: 100, b: 80 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'pomeranian_wagon', name: 'Pomeranian Wagon', type: BlockType.POMERANIAN_WAGON, color: { r: 200, g: 180, b: 140 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'terrier_tent', name: 'Terrier Tent', type: BlockType.TERRIER_TENT, color: { r: 140, g: 120, b: 90 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'wolf_folk_camp', name: 'Wolf Folk Camp', type: BlockType.WOLF_FOLK_CAMP, color: { r: 100, g: 110, b: 120 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'human_castle_spawner', name: 'Human Castle Spawner', type: BlockType.HUMAN_CASTLE_SPAWNER, color: { r: 150, g: 150, b: 160 }, isSolid: true, hardness: 150, isIndestructible: true },
    { id: 'human_outpost_spawner', name: 'Human Outpost Spawner', type: BlockType.HUMAN_OUTPOST_SPAWNER, color: { r: 160, g: 140, b: 120 }, isSolid: true, hardness: 120, isIndestructible: true },
    { id: 'dark_wizard_pedestal', name: 'Shadow Pedestal', type: BlockType.DARK_WIZARD_PEDESTAL, color: { r: 80, g: 0, b: 100 }, isSolid: true, hardness: 100, isIndestructible: true },
    { id: 'buggy_ramp', name: 'Buggy Ramp', type: BlockType.BUGGY_RAMP, color: { r: 139, g: 69, b: 19 }, isSolid: false, hardness: 50 },
    { id: 'sand_terror_altar', name: 'Sand Terror Altar', type: BlockType.SAND_TERROR_ALTAR, color: { r: 180, g: 150, b: 80 }, isSolid: true, hardness: 200, isIndestructible: true },
    { id: 'phantom_wizard_altar', name: 'Phantom Wizard Altar', type: BlockType.PHANTOM_WIZARD_ALTAR, color: { r: 100, g: 40, b: 180 }, isSolid: true, hardness: 200, isIndestructible: true },

    { id: 'stall_books', name: 'Books Stall', type: BlockType.STALL_BOOKS, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_staves', name: 'Staves Stall', type: BlockType.STALL_STAVES, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_swords', name: 'Swords Stall', type: BlockType.STALL_SWORDS, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_potions', name: 'Potions Stall', type: BlockType.STALL_POTIONS, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_ingots', name: 'Ingots Stall', type: BlockType.STALL_INGOTS, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_seeds', name: 'Seeds Stall', type: BlockType.STALL_SEEDS, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_fabric', name: 'Fabric Stall', type: BlockType.STALL_FABRIC, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_rune_keys', name: 'Rune Keys Stall', type: BlockType.STALL_RUNE_KEYS, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_blocks', name: 'Blocks Stall', type: BlockType.STALL_BLOCKS, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },
    { id: 'stall_leather', name: 'Leather Stall', type: BlockType.STALL_LEATHER, color: { r: 139, g: 69, b: 19 }, isSolid: true, isIndestructible: true },

    { id: 'glass', name: 'Glass', type: BlockType.GLASS, color: { r: 200, g: 250, b: 250 }, isSolid: true, hardness: 10 },
    { id: 'stone_staircase', name: 'Stone Staircase', type: BlockType.STONE_STAIRCASE, color: { r: 100, g: 100, b: 100 }, isSolid: false },
    { id: 'stone_door_closed', name: 'Stone Door Closed', type: BlockType.STONE_DOOR_CLOSED, color: { r: 105, g: 105, b: 105 }, isSolid: true },
    { id: 'stone_door_open', name: 'Stone Door Open', type: BlockType.STONE_DOOR_OPEN, color: { r: 105, g: 105, b: 105 }, isSolid: false },

    { id: 'archer_tent', name: 'Archer Tent', type: BlockType.ARCHER_TENT, color: { r: 160, g: 120, b: 80 }, isSolid: true, hardness: 50 },
    { id: 'dark_knight_tent', name: 'Dark Knight Spawner', type: BlockType.DARK_KNIGHT_TENT, color: { r: 30, g: 30, b: 40 }, isSolid: true, hardness: 80 },

    { id: 'quest_dungeon_spawner', name: 'Quest Dungeon', type: BlockType.QUEST_DUNGEON_SPAWNER, color: { r: 0, g: 0, b: 0 }, isSolid: true, isIndestructible: true },
    { id: 'quest_npc_spawner', name: 'Quest NPC Spawner', type: BlockType.QUEST_NPC_SPAWNER, color: { r: 0, g: 0, b: 0 }, isSolid: true, isIndestructible: true }
];
