import { BlockDef } from '../../registries/BlockRegistry';
import { BlockType } from '../../constants/BlockType';

export const STONE_BLOCKS: BlockDef[] = [
    {
        id: 'stone',
        name: 'Stone',
        type: BlockType.STONE,
        color: { r: 128, g: 128, b: 128 },
    },{
        id: 'gravestone',
        name: 'Gravestone',
        type: BlockType.GRAVESTONE,
        color: { r: 105, g: 105, b: 105 },
    },{
        id: 'castle_stone_old',
        name: 'Castle Stone',
        type: BlockType.CASTLE_STONE,
        color: { r: 120, g: 120, b: 125 },
    },{
        id: 'marble',
        name: 'Marble',
        type: BlockType.MARBLE,
        color: { r: 240, g: 240, b: 240 },
    },{
        id: 'black_marble',
        name: 'Black Marble',
        type: BlockType.BLACK_MARBLE,
        color: { r: 30, g: 30, b: 30 },
    },{
        id: 'green_marble',
        name: 'Green Marble',
        type: BlockType.GREEN_MARBLE,
        color: { r: 40, g: 100, b: 60 },
    },{
        id: 'obsidian',
        name: 'Obsidian',
        type: BlockType.OBSIDIAN,
        hardness: 200,
        color: { r: 20, g: 10, b: 30 },
    },{
        id: 'lava_rock',
        name: 'Lava Rock',
        type: BlockType.LAVA_ROCK,
        color: { r: 80, g: 30, b: 20 },
    },{
        id: 'dungeon_brick',
        name: 'Dungeon Brick',
        type: BlockType.DUNGEON_BRICK,
        isIndestructible: true,
        color: { r: 50, g: 50, b: 60 },
    },{
        id: 'abyssal_brick',
        name: 'Abyssal Brick',
        type: BlockType.ABYSSAL_BRICK,
        isIndestructible: true,
        color: { r: 20, g: 10, b: 20 },
    },{
        id: 'dungeon_brick_hard',
        name: 'Dungeon Brick Hard',
        type: BlockType.DUNGEON_BRICK_HARD,
        isIndestructible: true,
        color: { r: 35, g: 35, b: 45 },
    },{
        id: 'dungeon_brick_cracked',
        name: 'Dungeon Brick Cracked',
        type: BlockType.DUNGEON_BRICK_CRACKED,
        isIndestructible: true,
        color: { r: 85, g: 85, b: 95 },
    },{
        id: 'dungeon_brick_indestructible',
        name: 'Dungeon Brick Indestructible',
        type: BlockType.DUNGEON_BRICK_INDESTRUCTIBLE,
        isIndestructible: true,
        color: { r: 15, g: 15, b: 25 },
    },{
        id: 'red_stone',
        name: 'Red Stone',
        type: BlockType.RED_STONE,
        color: { r: 150, g: 80, b: 80 },
    },{
        id: 'red_marble',
        name: 'Red Marble',
        type: BlockType.RED_MARBLE,
        color: { r: 200, g: 150, b: 150 },
    },{
        id: 'black_stone',
        name: 'Black Stone',
        type: BlockType.BLACK_STONE,
        color: { r: 15, g: 15, b: 15 },
    },{
        id: 'green_stone',
        name: 'Green Stone',
        type: BlockType.GREEN_STONE,
        color: { r: 80, g: 140, b: 80 },
    },{
        id: 'blue_stone',
        name: 'Blue Stone',
        type: BlockType.BLUE_STONE,
        color: { r: 80, g: 100, b: 160 },
    },{
        id: 'blue_marble',
        name: 'Blue Marble',
        type: BlockType.BLUE_MARBLE,
        color: { r: 150, g: 180, b: 220 },
    },{
        id: 'orange_stone',
        name: 'Orange Stone',
        type: BlockType.ORANGE_STONE,
        color: { r: 160, g: 110, b: 70 },
    },{
        id: 'orange_marble',
        name: 'Orange Marble',
        type: BlockType.ORANGE_MARBLE,
        color: { r: 220, g: 180, b: 140 },
    },{
        id: 'purple_stone',
        name: 'Purple Stone',
        type: BlockType.PURPLE_STONE,
        color: { r: 120, g: 80, b: 150 },
    },{
        id: 'purple_marble',
        name: 'Purple Marble',
        type: BlockType.PURPLE_MARBLE,
        color: { r: 180, g: 150, b: 210 },
    },{
        id: 'yellow_stone',
        name: 'Yellow Stone',
        type: BlockType.YELLOW_STONE,
        color: { r: 180, g: 160, b: 90 },
    },{
        id: 'yellow_marble',
        name: 'Yellow Marble',
        type: BlockType.YELLOW_MARBLE,
        color: { r: 240, g: 230, b: 160 },
    },{
        id: 'brown_stone',
        name: 'Brown Stone',
        type: BlockType.BROWN_STONE,
        color: { r: 120, g: 90, b: 70 },
    },{
        id: 'brown_marble',
        name: 'Brown Marble',
        type: BlockType.BROWN_MARBLE,
        color: { r: 170, g: 140, b: 110 },
    },{
        id: 'black_fire_rock',
        name: 'Black Fire Rock',
        type: BlockType.BLACK_FIRE_ROCK,
        color: { r: 20, g: 10, b: 10 },
    },{
        id: 'moonstone',
        name: 'Moonstone',
        type: BlockType.MOONSTONE,
        color: { r: 220, g: 240, b: 255 },
    },{
        id: 'blood_stone',
        name: 'Blood Stone',
        type: BlockType.BLOOD_STONE,
        color: { r: 180, g: 20, b: 40 },
    },{
        id: 'sun_rock',
        name: 'Sun Rock',
        type: BlockType.SUN_ROCK,
        color: { r: 255, g: 220, b: 100 },
    },{
        id: 'coralline_rock',
        name: 'Coralline Rock',
        type: BlockType.CORALLINE_ROCK,
        color: { r: 255, g: 150, b: 140 },
    },{
        id: 'echo_stone',
        name: 'Echo Stone',
        type: BlockType.ECHO_STONE,
        color: { r: 160, g: 180, b: 200 },
    },{ id: 'stone_staircase', name: 'Stone Staircase', type: BlockType.STONE_STAIRCASE, color: { r: 100, g: 100, b: 100 }, isSolid: false },
    { id: 'runed_stone', name: 'Runed Stone', type: BlockType.RUNED_STONE, color: { r: 128, g: 128, b: 128 } },
    { id: 'runed_castle_stone', name: 'Runed Castle Stone', type: BlockType.RUNED_CASTLE_STONE, color: { r: 120, g: 120, b: 125 } },
    { id: 'runed_marble', name: 'Runed Marble', type: BlockType.RUNED_MARBLE, color: { r: 240, g: 240, b: 240 } },
    { id: 'runed_black_marble', name: 'Runed Black Marble', type: BlockType.RUNED_BLACK_MARBLE, color: { r: 30, g: 30, b: 30 } },
    { id: 'runed_green_marble', name: 'Runed Green Marble', type: BlockType.RUNED_GREEN_MARBLE, color: { r: 40, g: 100, b: 60 } },
    { id: 'runed_obsidian', name: 'Runed Obsidian', type: BlockType.RUNED_OBSIDIAN, color: { r: 20, g: 10, b: 30 }, hardness: 200 },
    { id: 'runed_red_stone', name: 'Runed Red Stone', type: BlockType.RUNED_RED_STONE, color: { r: 150, g: 80, b: 80 } },
    { id: 'runed_red_marble', name: 'Runed Red Marble', type: BlockType.RUNED_RED_MARBLE, color: { r: 200, g: 150, b: 150 } },
    { id: 'runed_black_stone', name: 'Runed Black Stone', type: BlockType.RUNED_BLACK_STONE, color: { r: 15, g: 15, b: 15 } },
    { id: 'runed_green_stone', name: 'Runed Green Stone', type: BlockType.RUNED_GREEN_STONE, color: { r: 80, g: 140, b: 80 } },
    { id: 'runed_blue_stone', name: 'Runed Blue Stone', type: BlockType.RUNED_BLUE_STONE, color: { r: 80, g: 100, b: 160 } },
    { id: 'runed_blue_marble', name: 'Runed Blue Marble', type: BlockType.RUNED_BLUE_MARBLE, color: { r: 150, g: 180, b: 220 } },
    { id: 'runed_orange_stone', name: 'Runed Orange Stone', type: BlockType.RUNED_ORANGE_STONE, color: { r: 160, g: 110, b: 70 } },
    { id: 'runed_orange_marble', name: 'Runed Orange Marble', type: BlockType.RUNED_ORANGE_MARBLE, color: { r: 220, g: 180, b: 140 } },
    { id: 'runed_purple_stone', name: 'Runed Purple Stone', type: BlockType.RUNED_PURPLE_STONE, color: { r: 120, g: 80, b: 150 } },
    { id: 'runed_purple_marble', name: 'Runed Purple Marble', type: BlockType.RUNED_PURPLE_MARBLE, color: { r: 180, g: 150, b: 210 } },
    { id: 'runed_yellow_stone', name: 'Runed Yellow Stone', type: BlockType.RUNED_YELLOW_STONE, color: { r: 180, g: 160, b: 90 } },
    { id: 'runed_yellow_marble', name: 'Runed Yellow Marble', type: BlockType.RUNED_YELLOW_MARBLE, color: { r: 240, g: 230, b: 160 } },
    { id: 'runed_brown_stone', name: 'Runed Brown Stone', type: BlockType.RUNED_BROWN_STONE, color: { r: 120, g: 90, b: 70 } },
    { id: 'runed_brown_marble', name: 'Runed Brown Marble', type: BlockType.RUNED_BROWN_MARBLE, color: { r: 170, g: 140, b: 110 } },
    { id: 'runed_moonstone', name: 'Runed Moonstone', type: BlockType.RUNED_MOONSTONE, color: { r: 220, g: 240, b: 255 } },
    { id: 'runed_blood_stone', name: 'Runed Blood Stone', type: BlockType.RUNED_BLOOD_STONE, color: { r: 180, g: 20, b: 40 } },
    { id: 'runed_echo_stone', name: 'Runed Echo Stone', type: BlockType.RUNED_ECHO_STONE, color: { r: 160, g: 180, b: 200 } },
    { id: 'runed_dungeon_brick', name: 'Runed Dungeon Brick', type: BlockType.RUNED_DUNGEON_BRICK, color: { r: 50, g: 50, b: 60 }, isIndestructible: true },
    { id: 'runed_abyssal_brick', name: 'Runed Abyssal Brick', type: BlockType.RUNED_ABYSSAL_BRICK, color: { r: 20, g: 10, b: 20 }, isIndestructible: true },
];