import { BlockType } from '../../constants/BlockType';
import { PlanetDef } from '../../registries/PlanetRegistry';

export const CORE_PLANETS: PlanetDef[] = [
    {
        id: 'HERAT',
        name: 'Herat',
        description: 'A temperate and familiar world.',
        surfaceBlock: BlockType.GRASS,
        dirtBlock: BlockType.DIRT,
        stoneBlock: BlockType.STONE,
        waterBlock: BlockType.WATER,
        woodBlock: BlockType.WOOD_LOG,
        leafBlock: BlockType.LEAVES,
        pineLeafBlock: BlockType.PINE_LEAVES,
        elevationMod: 12,
        baseElevation: 15,
        waterLevel: 10,
        oreMultiplier: 1,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.BEE_HIVE, chance: 0.15 },
            { block: BlockType.GOBLIN_CAMP, chance: 0.15 },
            { block: BlockType.ORC_TENT, chance: 0.10 },
            { block: BlockType.GOBLIN_SHAMAN_TENT, chance: 0.10 },
            { block: BlockType.BONE_PILE_SPAWNER, chance: 0.10 },
            { block: BlockType.ANT_HILL, chance: 0.10 },
            { block: BlockType.SPIDER_WEB, chance: 0.01 },
            { block: BlockType.DEMON_PORTAL, chance: 0.01 },
            { block: BlockType.HALFLING_HOUSE_SPAWNER, chance: 0.05 },
            { block: BlockType.PIT_BULL_TENT, chance: 0.04 },
            { block: BlockType.POMERANIAN_WAGON, chance: 0.04 },
            { block: BlockType.TERRIER_TENT, chance: 0.04 },
            { block: BlockType.WOLF_FOLK_CAMP, chance: 0.04 },
            { block: BlockType.HUMAN_CASTLE_SPAWNER, chance: 0.02 },
            { block: BlockType.HUMAN_OUTPOST_SPAWNER, chance: 0.02 },
            { block: BlockType.KING_SPAWNER, chance: 0.02 },
            { block: BlockType.QUEST_NPC_SPAWNER, chance: 0.03 },
            { block: BlockType.MERCHANT_TENT, chance: 0.03 },
            { block: BlockType.WANDERING_BARD_TENT, chance: 0.03 },
            { block: BlockType.PRIEST_TENT, chance: 0.02 },
            { block: BlockType.ARCHER_TENT, chance: 0.02 },
            { block: BlockType.DARK_KNIGHT_TENT, chance: 0.01 },
            { block: BlockType.TENT, chance: 0.05 },
            { block: BlockType.FAIRY_SPAWNER, chance: 0.05 }
        ],
        airColor: 'rgb(10, 35, 25)'
    },
    {
        id: 'ARETH',
        name: 'Areth',
        description: 'A treacherous volcanic planet.',
        surfaceBlock: BlockType.RED_DIRT,
        dirtBlock: BlockType.RED_STONE,
        stoneBlock: BlockType.OBSIDIAN,
        waterBlock: BlockType.LAVA,
        woodBlock: BlockType.RED_WOOD,
        leafBlock: BlockType.RED_LEAVES,
        pineLeafBlock: BlockType.RED_LEAVES,
        elevationMod: 25,
        baseElevation: 12,
        waterLevel: 10,
        oreMultiplier: 2,
        safeAreaMethod: 'BOX',
        spawnerTable: [
            { block: BlockType.KOBOLD_TENT, chance: 0.10 },
            { block: BlockType.KOBOLD_TENT_WARRIOR, chance: 0.10 },
            { block: BlockType.KOBOLD_TENT_TRAPPER, chance: 0.05 },
            { block: BlockType.KOBOLD_TENT_SHAMAN, chance: 0.05 },
            { block: BlockType.KOBOLD_TENT_BOMBER, chance: 0.05 },
            { block: BlockType.KOBOLD_TENT_DRAGONKEEPER, chance: 0.05 },
            { block: BlockType.DRAKE_NEST, chance: 0.15 },
            { block: BlockType.LAVA_POOL, chance: 0.20 },
            { block: BlockType.DRAGON_LAIR, chance: 0.15 },
            { block: BlockType.DRACONIC_SHRINE, chance: 0.10 }
        ],
        airColor: 'rgb(30, 0, 0)'
    },
    {
        id: 'RAETH',
        name: 'Raeth',
        description: 'A decaying world of obsidian dunes and floating aberrations.',
        surfaceBlock: BlockType.BLACK_SAND,
        dirtBlock: BlockType.BLACK_SAND,
        stoneBlock: BlockType.BLACK_STONE,
        waterBlock: BlockType.POISON_WATER,
        woodBlock: BlockType.BLACK_WOOD,
        leafBlock: BlockType.BLACK_LEAVES,
        pineLeafBlock: BlockType.BLACK_LEAVES,
        elevationMod: 20, // Tall sloping dunes
        baseElevation: 10,
        waterLevel: 5,
        oreMultiplier: 1.5,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.OBSERVER_SPAWNER, chance: 0.40 },
            { block: BlockType.SLUG_FOLK_MERCHANT, chance: 0.15 },
            { block: BlockType.BONE_PILE_SPAWNER, chance: 0.45 }
        ],
        airColor: 'rgb(20, 0, 40)' // Oppressive violet/dark purple
    },
    {
        id: 'TARHE',
        name: 'Tarhe',
        description: 'The dwarven homeworld. Entirely subterranean with massive ore veins.',
        surfaceBlock: BlockType.STONE, // No grass surface
        dirtBlock: BlockType.STONE,
        stoneBlock: BlockType.DEEP_SLATE,
        waterBlock: BlockType.LAVA,
        woodBlock: BlockType.MINE_SHAFT_WOOD,
        leafBlock: BlockType.LANTERN_BLOCK, // Substitute for leaves to light up the dark
        pineLeafBlock: BlockType.LANTERN_BLOCK,
        elevationMod: 40, // EXTREMELY high elevation variance for a lot of blocks (representing deep caves when inverted or parsed differently)
        baseElevation: 30, // Most of it should be ground
        waterLevel: 5,
        oreMultiplier: 5, // Ridiculous amounts of ore!
        safeAreaMethod: 'BOX',
        spawnerTable: [
            { block: BlockType.DWARF_SPAWNER, chance: 0.40 },
            { block: BlockType.GNOME_SPAWNER, chance: 0.30 },
            { block: BlockType.ROCK_GOLEM_SPAWNER, chance: 0.30 }
        ],
        airColor: 'rgb(5, 5, 5)' // Pitch black
    },
    {
        id: 'TERHA',
        name: 'Terha',
        description: 'The Orc and Goblin homeworld. Home to giants and colossal lizard titans.',
        surfaceBlock: BlockType.MUD,
        dirtBlock: BlockType.BROWN_DIRT,
        stoneBlock: BlockType.BROWN_STONE,
        waterBlock: BlockType.MUD,
        woodBlock: BlockType.BLACK_WOOD,
        leafBlock: BlockType.BLACK_LEAVES,
        pineLeafBlock: BlockType.BLACK_LEAVES,
        elevationMod: 10,
        baseElevation: 12,
        waterLevel: 8,
        oreMultiplier: 1.5,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.GOBLIN_CAMP, chance: 0.10 },
            { block: BlockType.GOBLIN_SHAMAN_TENT, chance: 0.05 },
            { block: BlockType.GOBLIN_TENT_ROCKHURLER, chance: 0.05 },
            { block: BlockType.GOBLIN_TENT_GARDENER, chance: 0.05 },
            { block: BlockType.GOBLIN_TENT_BOOMERANGER, chance: 0.05 },
            { block: BlockType.GOBLIN_TENT_ALCHEMIST, chance: 0.05 },
            { block: BlockType.GOBLIN_TENT_MINER, chance: 0.05 },
            { block: BlockType.ORC_TENT, chance: 0.10 },
            { block: BlockType.ORC_TENT_BRUTE, chance: 0.10 },
            { block: BlockType.ORC_TENT_SHAMAN, chance: 0.05 },
            { block: BlockType.ORC_TENT_HUNTER, chance: 0.05 },
            { block: BlockType.GIANT_CAMP, chance: 0.10 },
            { block: BlockType.TITAN_NEST, chance: 0.05 },
            { block: BlockType.SLIME_PUDDLE, chance: 0.05 },
            { block: BlockType.BONE_PILE_SPAWNER, chance: 0.10 }
        ],
        airColor: 'rgb(30, 25, 20)'
    },
    {
        id: 'HEART',
        name: 'Heart',
        description: 'An enchanted, magical elven realm.',
        surfaceBlock: BlockType.GRASS,
        dirtBlock: BlockType.PURPLE_DIRT,
        stoneBlock: BlockType.MARBLE,
        waterBlock: BlockType.WATER,
        woodBlock: BlockType.ANCIENT_WOOD,
        leafBlock: BlockType.ANCIENT_LEAVES,
        pineLeafBlock: BlockType.ANCIENT_LEAVES,
        elevationMod: 30, // High verticality
        baseElevation: 10,
        waterLevel: 5,
        oreMultiplier: 1.5,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.FAIRY_SPAWNER, chance: 0.30 },
            { block: BlockType.GRYPHON_NEST, chance: 0.15 },
            { block: BlockType.DARK_ELF_SPAWNER, chance: 0.20 },
            { block: BlockType.DARK_ELF_TENT, chance: 0.15 },
            { block: BlockType.LAVA_POOL, chance: 0.05 },
            { block: BlockType.BEE_HIVE, chance: 0.15 }
        ],
        airColor: 'rgb(20, 10, 40)'
    },
    {
        id: 'RATHE',
        name: 'Rathe',
        description: 'Endless scorching deserts. Home to Sphinx, Gargoyles, Gremlins, & Djinn.',
        surfaceBlock: BlockType.ORANGE_SAND,
        dirtBlock: BlockType.ORANGE_CLAY,
        stoneBlock: BlockType.ORANGE_STONE,
        waterBlock: BlockType.WATER,
        woodBlock: BlockType.YELLOW_WOOD,
        leafBlock: BlockType.YELLOW_LEAVES,
        pineLeafBlock: BlockType.YELLOW_LEAVES,
        elevationMod: 5,
        baseElevation: 15,
        waterLevel: 10,
        oreMultiplier: 1,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.DJINN_LAMP_SHRINE, chance: 0.20 },
            { block: BlockType.GARGOYLE_PEDESTAL, chance: 0.35 },
            { block: BlockType.GREMLIN_CAMP, chance: 0.30 },
            { block: BlockType.DEMON_PORTAL, chance: 0.10 },
            { block: BlockType.SPHINX_SPAWNER, chance: 0.05 }
        ],
        airColor: 'rgb(50, 40, 20)'
    },
    {
        id: 'THAER',
        name: 'Thaer',
        description: 'A lush, overgrown jungle teeming with beasts and nature.',
        surfaceBlock: BlockType.GREEN_DIRT,
        dirtBlock: BlockType.DIRT,
        stoneBlock: BlockType.GREEN_STONE,
        waterBlock: BlockType.WATER,
        woodBlock: BlockType.GREEN_WOOD,
        leafBlock: BlockType.GREEN_LEAVES,
        pineLeafBlock: BlockType.GREEN_LEAVES,
        elevationMod: 8,
        baseElevation: 15,
        waterLevel: 10,
        oreMultiplier: 1,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.BEE_HIVE, chance: 0.15 },
            { block: BlockType.ANT_HILL, chance: 0.14 },
            { block: BlockType.SQUIRREL_FOLK_TREEHOUSE, chance: 0.25 },
            { block: BlockType.BEAST_CAMP, chance: 0.30 },
            { block: BlockType.BEAST_TAMER_CAMP, chance: 0.15 },
            { block: BlockType.SPIDER_WEB, chance: 0.01 }
        ],
        airColor: 'rgb(0, 40, 10)'
    },
    {
        id: 'ATHER',
        name: 'Ather',
        description: 'A realm of colossal fungi and clay.',
        surfaceBlock: BlockType.RED_CLAY,
        dirtBlock: BlockType.YELLOW_CLAY,
        stoneBlock: BlockType.YELLOW_STONE,
        waterBlock: BlockType.WATER,
        woodBlock: BlockType.GIANT_MUSHROOM_STALK,
        leafBlock: BlockType.GIANT_MUSHROOM_CAP_RED,
        pineLeafBlock: BlockType.GIANT_MUSHROOM_CAP_BROWN,
        elevationMod: 15,
        baseElevation: 15,
        waterLevel: 10,
        oreMultiplier: 1.5,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.FUNGI_FOLK_TENT, chance: 0.15 },
            { block: BlockType.OGRE_DEN, chance: 0.10 },
            { block: BlockType.TROLL_CAVE, chance: 0.10 },
            { block: BlockType.GIANT_CAMP, chance: 0.10 },
            { block: BlockType.CLAY_ORE, chance: 0.30 },
            { block: BlockType.GLOWCAP_MUSHROOM, chance: 0.25 }
        ],
        airColor: 'rgb(20, 10, 30)'
    },
    {
        id: 'THREA',
        name: 'Threa',
        description: 'The Biodiverse Melting Pot. A majestic world of dramatic alpine peaks, deep canyons, tropical thickets, freezing tundras, and magic crystal forests.',
        surfaceBlock: BlockType.GRASS,
        dirtBlock: BlockType.DIRT,
        stoneBlock: BlockType.STONE,
        waterBlock: BlockType.WATER,
        woodBlock: BlockType.WOOD_LOG,
        leafBlock: BlockType.LEAVES,
        pineLeafBlock: BlockType.PINE_LEAVES,
        elevationMod: 12,
        baseElevation: 15,
        waterLevel: 10,
        oreMultiplier: 1,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.BEE_HIVE, chance: 0.10 },
            { block: BlockType.GOBLIN_CAMP, chance: 0.10 },
            { block: BlockType.ORC_TENT, chance: 0.05 },
            { block: BlockType.BONE_PILE_SPAWNER, chance: 0.10 }
        ],
        airColor: 'rgb(20, 25, 30)'
    },
    {
        id: 'THERA',
        name: 'Thera',
        description: 'A prehistoric, tropical world of dinosaurs, canyons, and ruins.',
        surfaceBlock: BlockType.MUD,
        dirtBlock: BlockType.MUD,
        stoneBlock: BlockType.STONE,
        waterBlock: BlockType.SWAMP_WATER,
        woodBlock: BlockType.TROPICAL_WOOD,
        leafBlock: BlockType.TROPICAL_LEAVES,
        pineLeafBlock: BlockType.FERN,
        elevationMod: 30, // For sweeping deep canyons
        baseElevation: 15,
        waterLevel: 8,
        oreMultiplier: 1.2,
        safeAreaMethod: 'RADIAL',
        spawnerTable: [
            { block: BlockType.TRICERA_TENT, chance: 0.20 },
            { block: BlockType.RAPTOR_TENT, chance: 0.25 },
            { block: BlockType.FROG_TENT, chance: 0.20 },
            { block: BlockType.BONE_PILE_SPAWNER, chance: 0.35 }
        ],
        airColor: 'rgb(25, 40, 25)'
    },
    {
        id: 'NORTH_HEART',
        name: 'North Heart',
        description: 'A freezing, treacherous region of Heart inhabited by winter elves and yeti.',
        surfaceBlock: BlockType.SNOW,
        dirtBlock: BlockType.PERMAFROST,
        stoneBlock: BlockType.ICE,
        waterBlock: BlockType.GLACIAL_ICE,
        woodBlock: BlockType.FROZEN_WOOD,
        leafBlock: BlockType.FROZEN_LEAVES,
        pineLeafBlock: BlockType.FROZEN_LEAVES,
        elevationMod: 25, // mountainous
        baseElevation: 15,
        waterLevel: 10,
        oreMultiplier: 3.0,
        safeAreaMethod: 'BOX',
        spawnerTable: [
            { block: BlockType.WINTER_ELF_TENT, chance: 0.25 },
            { block: BlockType.YETI_CAVE, chance: 0.25 },
            { block: BlockType.FROST_CASTER_TENT, chance: 0.15 },
            { block: BlockType.SHRINE, chance: 0.05 }
        ],
        airColor: 'rgb(200, 230, 255)'
    }
];
