import type { Item } from '../../../registries/ItemRegistry';

export const BOWS_AND_RANGED_ITEMS: Record<string, Item> = {
    'moose_antler_bow': {
        id: "moose_antler_bow",
        name: "Antler Bow",
        description: "A massive bow carved from a Moose Antler. Very powerful.",
        category: "WEAPON",
        twoHanded: true,
        damage: 35,
        reach: 25.0,
        cooldown: 0.8,
        spread: 0.05,
        projectileSpeed: 25.0,
        projectileColor: "#d7ccc8",
        stackable: false,
        maxStack: 1
    },
    'shortbow_1': {
        id: "shortbow_1",
        name: "Wooden Shortbow",
        description: "A simple bow. Good for keeping enemies at a distance.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 8,
        cooldown: 0.8,
        projectileSpeed: 20
    },
    'iron_shortbow': {
        id: "iron_shortbow",
        name: "Iron Shortbow",
        description: "A sturdy bow reinforced with iron.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 15,
        cooldown: 0.7,
        projectileSpeed: 25
    },
    'elven_longbow': {
        id: "elven_longbow",
        name: "Elven Longbow",
        description: "A finely crafted bow of ancient wood. Hold attack for 1s to charge a Multi-Shot (Consumes 15 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 22,
        cooldown: 0.6,
        projectileSpeed: 30,
        secondaryAbility: "BOW_MULTI_SHOT",
        chargeTime: 1.0,
        chargeManaCost: 15
    },
    'dragon_bone_bow': {
        id: "dragon_bone_bow",
        name: "Dragon Bone Bow",
        description: "Carved from the bones of a drake. Hold attack for 1.5s to charge an Explosive Shot (Consumes 25 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 35,
        cooldown: 1.0,
        projectileSpeed: 35,
        secondaryAbility: "BOW_EXPLOSIVE_SHOT",
        chargeTime: 1.5,
        chargeManaCost: 25
    },
    'wooden_boomerang': {
        id: "wooden_boomerang",
        name: "Wooden Boomerang",
        description: "A curved piece of wood that returns when thrown. Equipping unlocks the Boomerang talent.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 5,
        cooldown: 1,
        projectileSpeed: 12
    },
    'green_metal_boomerang': {
        id: "green_metal_boomerang",
        name: "Green Metal Boomerang",
        description: "A finely crafted boomerang. Hold attack to charge a Spread Shot (Consumes 15 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 15,
        cooldown: 0.8,
        projectileSpeed: 16,
        secondaryAbility: "BOOMERANG_SPREAD_SHOT",
        chargeTime: 1.0,
        chargeManaCost: 15
    },
    'red_metal_boomerang': {
        id: "red_metal_boomerang",
        name: "Red Metal Boomerang",
        description: "A heavy, seeking boomerang. Hold attack to charge a Seeking Shot (Consumes 20 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 25,
        cooldown: 0.8,
        projectileSpeed: 18,
        secondaryAbility: "BOOMERANG_SEEKER_SHOT",
        chargeTime: 1.0,
        chargeManaCost: 20
    },
    'bone_boomerang': {
        id: "bone_boomerang",
        name: "Bone Boomerang",
        description: "A jagged boomerang made of sturdy bone.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 8,
        cooldown: 0.9,
        projectileSpeed: 13
    },
    'copper_boomerang': {
        id: "copper_boomerang",
        name: "Copper Boomerang",
        description: "A sturdy copper boomerang.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 10,
        cooldown: 0.9,
        projectileSpeed: 14
    },
    'iron_boomerang': {
        id: "iron_boomerang",
        name: "Iron Boomerang",
        description: "A heavy iron boomerang. Hard hitting but flies a bit slower.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 16,
        cooldown: 1.0,
        projectileSpeed: 12
    },
    'mithril_boomerang': {
        id: "mithril_boomerang",
        name: "Mithril Boomerang",
        description: "An incredibly light and fast boomerang. Hold attack to charge a Spread Shot.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 30,
        cooldown: 0.6,
        projectileSpeed: 22,
        secondaryAbility: "BOOMERANG_SPREAD_SHOT",
        chargeTime: 0.8,
        chargeManaCost: 10
    },
    'ice_boomerang': {
        id: "ice_boomerang",
        name: "Ice Boomerang",
        description: "A chilling boomerang that freezes enemies on hit.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 18,
        cooldown: 0.9,
        projectileSpeed: 18,
        statusEffect: { type: 'chill', chance: 1.0, duration: 2.0 },
    },
    'magma_boomerang': {
        id: "magma_boomerang",
        name: "Magma Boomerang",
        description: "A scorching boomerang that burns enemies on hit.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 22,
        cooldown: 0.9,
        projectileSpeed: 18,
        statusEffect: { type: 'burn', chance: 1.0, duration: 4.0 },
    },
    'cactus_boomerang': {
        id: "cactus_boomerang",
        name: "Cactus Boomerang",
        description: "A prickly boomerang. It has a chance to bleed enemies.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 12,
        cooldown: 0.8,
        projectileSpeed: 14,
        statusEffect: { type: 'bleed', chance: 0.5, duration: 3.0 },
    },
    'lightning_boomerang': {
        id: "lightning_boomerang",
        name: "Lightning Boomerang",
        description: "A crackling electric boomerang.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 28,
        cooldown: 0.7,
        projectileSpeed: 24,
        secondaryAbility: "BOOMERANG_SPREAD_SHOT",
        chargeTime: 0.6,
        chargeManaCost: 12
    },
    'crystal_boomerang': {
        id: "crystal_boomerang",
        name: "Crystal Boomerang",
        description: "A beautiful crystal boomerang. Very fragile but sharp.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 35,
        cooldown: 0.8,
        projectileSpeed: 20
    },
    'obsidian_boomerang': {
        id: "obsidian_boomerang",
        name: "Obsidian Boomerang",
        description: "An incredibly sharp obsidian boomerang. It pierces through enemies.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 42,
        cooldown: 1.0,
        projectileSpeed: 16
    },
    'splitting_boomerang': {
        id: "splitting_boomerang",
        name: "Splitting Boomerang",
        description: "A magical boomerang that splits into 3 once thrown.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 20,
        cooldown: 1.2,
        projectileSpeed: 16,
        secondaryAbility: "BOOMERANG_SPREAD_SHOT", // It can still have spread shot!
        chargeTime: 1.0,
        chargeManaCost: 10
    },
    'dragon_boomerang': {
        id: "dragon_boomerang",
        name: "Dragon Boomerang",
        description: "A massive boomerang radiating dragon fire.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 75,
        cooldown: 1.3,
        projectileSpeed: 22,
        statusEffect: { type: 'burn', chance: 1.0, duration: 6.0 },
    },
    'blood_boomerang': {
        id: "blood_boomerang",
        name: "Blood Boomerang",
        description: "A sinister boomerang that drains life on hit.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 45,
        cooldown: 0.8,
        projectileSpeed: 21,
        secondaryAbility: "BOOMERANG_SEEKER_SHOT",
        chargeTime: 0.8,
        chargeManaCost: 18,
        lifesteal: 0.25
    },
    'void_boomerang': {
        id: "void_boomerang",
        name: "Void Boomerang",
        description: "An abyssal boomerang that rapidly seeks its targets.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 50,
        cooldown: 0.5,
        projectileSpeed: 28,
        secondaryAbility: "BOOMERANG_SEEKER_SHOT",
        chargeTime: 0.5,
        chargeManaCost: 15
    },
    'dark_elf_bow': {
        id: "dark_elf_bow",
        name: "Dark Elf Bow",
        description: "A shadowy bow that fires with lethal precision.",
        type: "RANGED",
        category: "WEAPON",
        damage: 25,
        reach: 22,
        cooldown: 0.5,
        ammoType: "ARROW",
        projectileSpeed: 20
    },
    'gnomish_crossbow': {
        id: "gnomish_crossbow",
        name: "Gnomish Repeater Crossbow",
        description: "A complex mechanical marvel that fires bolts at extreme velocities.",
        type: "RANGED",
        category: "WEAPON",
        damage: 18,
        reach: 25,
        cooldown: 0.2, // Very fast fire rate
        ammoType: "ARROW",
        projectileSpeed: 30
    },
    'star_metal_bow': {
        id: "star_metal_bow",
        name: "Star Metal Bow",
        description: "An incredibly cold bow, drawn by star metal tension.",
        type: "RANGED",
        category: "WEAPON",
        damage: 35,
        reach: 22,
        cooldown: 0.6,
        ammoType: "ARROW",
        projectileSpeed: 24,
        damageType: 'ICE',
        statusEffect: { type: 'chill', chance: 0.4, duration: 4.0 }
    },
    'star_metal_boomerang': {
        id: "star_metal_boomerang",
        name: "Star Metal Boomerang",
        description: "A fast, deadly returning star metal boomerang.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 28,
        cooldown: 0.6,
        projectileSpeed: 20,
        damageType: 'ICE',
        statusEffect: { type: 'chill', chance: 0.3, duration: 3.0 }
    }
};
