import type { Item } from '../../../registries/ItemRegistry';

export const STAVES_ITEMS: Record<string, Item> = {
    'travelers_staff_acid': {
        id: "travelers_staff_acid",
        name: "Traveler's Staff of Acid",
        description: "Fires an acid bolt. Hold attack for 1.5s then release to Blink.",
        type: "MAGIC_RANGED",
        damage: 25,
        reach: 18,
        cooldown: 0.8,
        projectileSpeed: 10,
        projectileColor: "#22c55e",
        spellId: "acid_bolt",
        damageType: "ACID",
        manaCost: 8,
        secondaryAbility: "BLINK",
        chargeTime: 1.5,
        chargeManaCost: 30,
        category: "WEAPON",
        maxStack: 1
    },
    'staff_fire_ranged': {
        id: "staff_fire_ranged",
        name: "Staff of Firebolts",
        description: "A wooden staff topped with a glowing ruby. Shoots bolts of fire.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "FIRE",
        twoHanded: true,
        damage: 15,
        cooldown: 0.8,
        projectileSpeed: 12
    },
    'staff_ice_aoe': {
        id: "staff_ice_aoe",
        name: "Staff of Frost Nova",
        description: "An icy staff that unleashes a freezing blast around the caster.",
        category: "WEAPON",
        type: "MAGIC_AOE",
        damageType: "ICE",
        twoHanded: true,
        damage: 12,
        reach: 3.5,
        cooldown: 1.5
    },
    'staff_lightning_ranged': {
        id: "staff_lightning_ranged",
        name: "Staff of Sparks",
        description: "Crackles with electricity. Fires fast-moving lightning projectiles.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "LIGHTNING",
        twoHanded: true,
        damage: 10,
        cooldown: 0.5,
        projectileSpeed: 25
    },
    'staff_arcane_aoe': {
        id: "staff_arcane_aoe",
        name: "Staff of Arcane Burst",
        description: "Releases a wave of pure arcane energy in a wide area.",
        category: "WEAPON",
        type: "MAGIC_AOE",
        damageType: "ARCANE",
        twoHanded: true,
        damage: 20,
        reach: 4,
        cooldown: 2
    },
    'staff_inferno': {
        id: "staff_inferno",
        name: "Staff of the Inferno",
        description: "Channels intense flames. Hold attack to call down a meteor.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "FIRE",
        twoHanded: true,
        damage: 25,
        cooldown: 1,
        projectileSpeed: 10,
        spellId: "fire_bolt",
        manaCost: 5,
        secondaryAbility: "METEOR",
        chargeTime: 2,
        chargeManaCost: 40
    },
    'staff_necromancer': {
        id: "staff_necromancer",
        name: "Necromancer's Crook",
        description: "A twisted staff of bone. Hold attack to summon a skeleton minion.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ACID",
        twoHanded: true,
        damage: 15,
        cooldown: 0.8,
        projectileSpeed: 12,
        spellId: "acid_bolt",
        manaCost: 5,
        secondaryAbility: "SUMMON_SKELETON",
        chargeTime: 1.5,
        chargeManaCost: 35
    },
    'amber_staff_dino': {
        id: "amber_staff_dino",
        name: "Amber Staff of Thera",
        description: "A staff topped with a glowing chunk of ancient amber. Hold attack to summon a Wild Raptor.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "PHYSICAL",
        twoHanded: true,
        damage: 22,
        cooldown: 0.7,
        projectileSpeed: 15,
        spellId: "plasma_orb",
        manaCost: 8,
        secondaryAbility: "SUMMON_WILD_RAPTOR",
        chargeTime: 2.0,
        chargeManaCost: 45
    },
    'staff_grove': {
        id: "staff_grove",
        name: "Staff of the Grove",
        description: "A living branch. Hold attack to root nearby enemies.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "PHYSICAL",
        twoHanded: true,
        damage: 12,
        cooldown: 0.6,
        projectileSpeed: 15,
        spellId: "arcane_bolt",
        manaCost: 4,
        secondaryAbility: "ROOT",
        chargeTime: 1.5,
        chargeManaCost: 25
    },
    'staff_heavens': {
        id: "staff_heavens",
        name: "Staff of the Heavens",
        description: "Crackles with energy. Hold attack for a lightning strike.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "LIGHTNING",
        twoHanded: true,
        damage: 20,
        cooldown: 0.9,
        projectileSpeed: 18,
        spellId: "lightning_bolt",
        manaCost: 6,
        secondaryAbility: "LIGHTNING_STRIKE",
        chargeTime: 2,
        chargeManaCost: 35
    },
    'staff_magma': {
        id: "staff_magma",
        name: "Magma Channeler",
        description: "Radiates heat. Hold attack to create a lava puddle at cursor.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "FIRE",
        twoHanded: true,
        damage: 18,
        cooldown: 1,
        projectileSpeed: 10,
        spellId: "fire_bolt",
        manaCost: 5,
        secondaryAbility: "LAVA_PUDDLE",
        chargeTime: 1.5,
        chargeManaCost: 20
    },
    'staff_glacial': {
        id: "staff_glacial",
        name: "Glacial Staff",
        description: "Freezing to the touch. Causes target to be slowed. Hold attack for Frost Nova.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ICE",
        twoHanded: true,
        damage: 16,
        cooldown: 0.8,
        projectileSpeed: 12,
        spellId: "ice_bolt",
        manaCost: 5,
        secondaryAbility: "FROST_NOVA",
        chargeTime: 2,
        chargeManaCost: 30,
        statusEffect: { type: 'chill', chance: 1.0, duration: 4.0 }
    },
    'staff_void': {
        id: "staff_void",
        name: "Void Staff",
        description: "Absorbs all light. Hold attack to conjure a Black Hole.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ARCANE",
        twoHanded: true,
        damage: 30,
        cooldown: 1.5,
        projectileSpeed: 8,
        spellId: "arcane_bolt",
        manaCost: 10,
        secondaryAbility: "BLACK_HOLE",
        chargeTime: 3,
        chargeManaCost: 60
    },
    'staff_druid': {
        id: "staff_druid",
        name: "Staff of the Druid",
        description: "Teems with life. Hold attack for Mass Heal.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ACID",
        twoHanded: true,
        damage: 10,
        cooldown: 0.5,
        projectileSpeed: 14,
        spellId: "acid_bolt",
        manaCost: 3,
        secondaryAbility: "MASS_HEAL",
        chargeTime: 2.5,
        chargeManaCost: 45
    },
    'staff_time': {
        id: "staff_time",
        name: "Time-Mender's Staff",
        description: "Distorts reality. Hold attack to stop time.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ARCANE",
        twoHanded: true,
        damage: 22,
        cooldown: 1.2,
        projectileSpeed: 20,
        spellId: "arcane_bolt",
        manaCost: 8,
        secondaryAbility: "TIME_STOP",
        chargeTime: 3,
        chargeManaCost: 80
    },
    'staff_wind': {
        id: 'staff_wind',
        name: 'Staff of the Wind',
        description: 'Light as a feather. Hold attack to push enemies back.',
        category: 'WEAPON',
        type: 'MAGIC_RANGED',
        damageType: 'ARCANE',
        twoHanded: true,
        damage: 14,
        cooldown: 0.7,
        projectileSpeed: 16,
        spellId: 'arcane_bolt',
        manaCost: 4,
        secondaryAbility: 'PUSH_BACK',
        chargeTime: 1,
        chargeManaCost: 15
    },
    'volcano_wand': {
        id: 'volcano_wand',
        name: 'Volcano Wand',
        description: 'Constantly erupts with volcanic magic.',
        category: 'WEAPON',
        type: 'MAGIC_RANGED',
        damageType: 'FIRE',
        twoHanded: false,
        damage: 40,
        cooldown: 0.2,
        projectileSpeed: 18,
        spellId: 'fire_bolt',
        manaCost: 3
    },
};
