import type { Item } from '../../../registries/ItemRegistry';

export const SWORDS_ITEMS: Record<string, Item> = {

    'infernal_sword': {
        id: 'infernal_sword',
        name: 'Infernal Greatsword',
        description: 'A blade engulfed in everlasting flames.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: true,
        damage: 65,
        reach: 4.0,
        cooldown: 0.7,
        spread: 0.7,
        damageType: 'FIRE',
        statusEffect: { type: 'burn', chance: 0.5, duration: 4.0 }
    },
    'frostmourne_sword': {
        id: 'frostmourne_sword',
        name: 'Glacial Blade',
        description: 'A sword that emanates pure cold.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: true,
        damage: 60,
        reach: 3.5,
        cooldown: 0.6,
        spread: 0.5,
        damageType: 'ICE',
        statusEffect: { type: 'chill', chance: 0.6, duration: 5.0 }
    },
    'stormcaller_sword': {
        id: 'stormcaller_sword',
        name: 'Thunder Edge',
        description: 'Crackling with lightning with every swing.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 55,
        reach: 3.0,
        cooldown: 0.4,
        spread: 0.6,
        damageType: 'LIGHTNING'
    },
    'void_sword': {
        id: 'void_sword',
        name: 'Void Cleaver',
        description: 'A sword that cuts through reality itself.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: true,
        damage: 90,
        reach: 5.0,
        cooldown: 1.2,
        spread: 0.8,
        damageType: 'ARCANE',
        lifesteal: 0.2
    },
    'excalibur_sword': {
        id: 'excalibur_sword',
        name: 'Excalibur',
        description: 'The legendary sword of pure light.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 75,
        reach: 3.5,
        cooldown: 0.5,
        spread: 0.6,
        damageType: 'MAGIC'
    },

    'abyssal_sword': {
        id: "abyssal_sword",
        name: "Abyssal Greatsword",
        description: "A massive blade forged in the dark depths. Drains life from enemies.",
        category: "WEAPON",
        twoHanded: true,
        damage: 45,
        reach: 3.5,
        cooldown: 0.8,
        spread: 0.6,
        lifesteal: 0.1
    },
    'wooden_sword': {
        id: "wooden_sword",
        name: "Wooden Sword",
        description: "A basic training sword made of wood.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 8,
        reach: 1,
        cooldown: 0.5,
        spread: 0.6
    },
    'copper_broadsword': {
        id: "copper_broadsword",
        name: "Copper Broadsword",
        description: "A simple but effective broadsword made of copper.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 12,
        reach: 1.2,
        cooldown: 0.6,
        spread: 0.8
    },
    'iron_longsword': {
        id: "iron_longsword",
        name: "Iron Longsword",
        description: "A well-crafted longsword made of iron.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 18,
        reach: 1.4,
        cooldown: 0.7,
        spread: 1
    },
    'flame_blade': {
        id: "flame_blade",
        name: "Flame Blade",
        description: "A blade wreathed in magical fire. Chance to burn enemies.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 22,
        reach: 1.5,
        cooldown: 0.7,
        spread: 1.2,
        statusEffect: { type: 'burn', chance: 0.3, duration: 3.0 }
    },
    'mithril_greatsword': {
        id: "mithril_greatsword",
        name: "Mithril Greatsword",
        description: "A legendary greatsword forged from mithril.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: true,
        damage: 35,
        reach: 2,
        cooldown: 1,
        spread: 1.8
    },
    'sword_1': {
        id: "sword_1",
        name: "Steel Sword",
        description: "A standard issue broadsword. Reliable and balanced.",
        category: "WEAPON",
        twoHanded: false,
        damage: 10,
        reach: 1.2,
        cooldown: 0.6,
        spread: 0.8
    },
    'greatsword_1': {
        id: "greatsword_1",
        name: "Iron Greatsword",
        description: "A massive two-handed blade. Slow but devastating.",
        category: "WEAPON",
        twoHanded: true,
        damage: 25,
        reach: 1.8,
        cooldown: 1.2,
        spread: 1.5
    },
    'obsidian_sword': {
        id: "obsidian_sword",
        name: "Obsidian Greatsword",
        description: "A blade made of pure draconic obsidian. Extremely volatile.",
        category: "WEAPON",
        twoHanded: true,
        damage: 65,
        reach: 2.0,
        cooldown: 0.9,
        spread: 1.8
    },
    'dark_elf_blade': {
        id: "dark_elf_blade",
        name: "Dark Elf Blade",
        description: "A wicked, curved blade favored by dark elves. Coated in strange poison.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 22,
        reach: 1.2,
        cooldown: 0.4,
        spread: 0.5,
        damageType: "ACID",
        statusEffect: { type: 'poison', chance: 0.5, duration: 5.0 }
    },
    'troll_tusk_sword': {
        id: 'troll_tusk_sword',
        name: 'Troll Tusk Sword',
        description: 'A brutal, curved blade carved from a cave troll\'s tusk.',
        category: 'WEAPON',
        twoHanded: false,
        damage: 38,
        reach: 1.8,
        cooldown: 0.8,
        spread: 0.7
    },
    'shadow_blade': {
        id: 'shadow_blade',
        name: 'Phantom Shadow Blade',
        description: 'A blade of condensed void logic. Heals you as you strike.',
        category: 'WEAPON',
        twoHanded: false,
        damage: 55,
        reach: 1.5,
        cooldown: 0.4,
        spread: 0.8,
        damageType: 'ARCANE',
        lifesteal: 0.2,
        itemColor: '#1a0033'
    },
    'astral_edge': {
        id: 'astral_edge',
        name: 'Astral Edge',
        description: 'Forged from a fallen star, it gleams with celestial energy.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 80,
        reach: 1.6,
        cooldown: 0.5,
        spread: 0.8,
        damageType: 'MAGIC',
        secondaryAbility: 'SPIN_LIGHT_BURST',
        swordBeamModifier: 'HOMING',
        itemColor: '#e6f2ff'
    },
    'bloodletter': {
        id: 'bloodletter',
        name: 'Bloodletter',
        description: 'A cruel blade that drinks the life of its victims.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: true,
        damage: 75,
        reach: 1.8,
        cooldown: 0.8,
        spread: 1.2,
        damageType: 'PHYSICAL',
        lifesteal: 0.35,
        secondaryAbility: 'SPIN_BLOOD_THIRST',
        itemColor: '#8a0303'
    },
    'sword_of_creator': {
        id: 'sword_of_creator',
        name: 'Sword of the Creator',
        description: 'A legendary weapon said to have carved the continents.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 95,
        reach: 2.0,
        cooldown: 0.6,
        spread: 1.0,
        damageType: 'MAGIC',
        secondaryAbility: 'SPIN_SPECTRAL_BLADES',
        swordBeamModifier: 'BURST',
        itemColor: '#ffd700'
    },
    'blightbringer': {
        id: 'blightbringer',
        name: 'Blightbringer',
        description: 'Wreathed in a sickening aura of decay and rot.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: true,
        damage: 85,
        reach: 2.1,
        cooldown: 0.9,
        spread: 1.5,
        damageType: 'ACID',
        statusEffect: { type: 'poison', chance: 1.0, duration: 8.0 },
        secondaryAbility: 'SPIN_POISON_WAVE',
        itemColor: '#33cc33'
    },
    'tempest_render': {
        id: 'tempest_render',
        name: 'Tempest Render',
        description: 'Crackling with the raw fury of a storm.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 88,
        reach: 1.7,
        cooldown: 0.4,
        spread: 0.9,
        damageType: 'LIGHTNING',
        swordBeamModifier: 'BOUNCE',
        secondaryAbility: 'SPIN_TELEPORT_STRIKE',
        itemColor: '#00e6e6'
    },
    'dragon_fang_sword': {
        id: 'dragon_fang_sword',
        name: 'Dragon Fang Blade',
        description: 'Carved from a massive dragon tooth, still burning.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 70,
        reach: 1.5,
        cooldown: 0.5,
        spread: 0.7,
        damageType: 'FIRE',
        statusEffect: { type: 'burn', chance: 0.6, duration: 5.0 },
        secondaryAbility: 'SPIN_DRAGON_BREATH',
        swordBeamModifier: 'GIANT',
        itemColor: '#ff6600'
    },
    'star_metal_sword': {
        id: 'star_metal_sword',
        name: 'Star Metal Sword',
        description: 'An elegant blade forged from falling stars, cold to the touch.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 55,
        reach: 3.5,
        cooldown: 0.4,
        spread: 0.4,
        damageType: 'ICE',
        statusEffect: { type: 'chill', chance: 0.3, duration: 4.0 },
        swordBeamModifier: 'STANDARD',
        itemColor: '#5099ff'
    },
    'star_metal_greatsword': {
        id: 'star_metal_greatsword',
        name: 'Star Metal Greatsword',
        description: 'A massive cleaver of star metal. It feels surprisingly light.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: true,
        damage: 85,
        reach: 5.5,
        cooldown: 0.9,
        spread: 0.8,
        damageType: 'ICE',
        statusEffect: { type: 'chill', chance: 0.6, duration: 6.0 },
        swordBeamModifier: 'GIANT',
        itemColor: '#4088ee'
    },
    'amber_sword': {
        id: 'amber_sword',
        name: 'Amber Sword',
        description: 'A glowing orange blade carved entirely out of hardened amber. Fast and light.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: false,
        damage: 42,
        reach: 1.6,
        cooldown: 0.4,
        spread: 0.5,
        damageType: 'PHYSICAL',
        swordBeamModifier: 'STANDARD',
        itemColor: '#ffbf00'
    },
    'amber_greatsword': {
        id: 'amber_greatsword',
        name: 'Amber Greatsword',
        description: 'A massive blade of fossilized resin. It traps the warmth of the sun.',
        category: 'WEAPON',
        type: 'MELEE',
        twoHanded: true,
        damage: 65,
        reach: 2.8,
        cooldown: 1.0,
        spread: 0.8,
        damageType: 'PHYSICAL',
        swordBeamModifier: 'GIANT',
        itemColor: '#ffb000'
    }
};
