import type { Item } from '../../registries/ItemRegistry';

export const WEAPON_ITEMS: Record<string, Item> = {
    'travelers_staff_acid': {
        id: "travelers_staff_acid",
        name: "Traveler's Staff of Acid",
        description: "Fires an acid bolt. Hold attack for 1.5s then release to Blink.",
        type: "MAGIC_RANGED",
        damage: 25,
        reach: 18,
        cooldown: 0.8,
        projectileSpeed: 10,
        projectileColor: "#22c55e",
        spellId: "acid_bolt",
        damageType: "ACID",
        manaCost: 8,
        secondaryAbility: "BLINK",
        chargeTime: 1.5,
        chargeManaCost: 30,
        category: "WEAPON",
        maxStack: 1
    },
    'abyssal_sword': {
        id: "abyssal_sword",
        name: "Abyssal Greatsword",
        description: "A massive blade forged in the dark depths. Drains life from enemies.",
        category: "WEAPON",
        twoHanded: true,
        damage: 45,
        reach: 3.5,
        cooldown: 0.8,
        spread: 0.6,
        lifesteal: 0.1
    },
    'dagger_1': {
        id: "dagger_1",
        name: "Iron Dagger",
        description: "A short, quick blade. Good for close encounters.",
        category: "WEAPON",
        twoHanded: false,
        damage: 5,
        reach: 0.8,
        cooldown: 0.3,
        spread: 0.4
    },
    'wooden_sword': {
        id: "wooden_sword",
        name: "Wooden Sword",
        description: "A basic training sword made of wood.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 8,
        reach: 1,
        cooldown: 0.5,
        spread: 0.6
    },
    'copper_broadsword': {
        id: "copper_broadsword",
        name: "Copper Broadsword",
        description: "A simple but effective broadsword made of copper.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 12,
        reach: 1.2,
        cooldown: 0.6,
        spread: 0.8
    },
    'iron_longsword': {
        id: "iron_longsword",
        name: "Iron Longsword",
        description: "A well-crafted longsword made of iron.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 18,
        reach: 1.4,
        cooldown: 0.7,
        spread: 1
    },
    'flame_blade': {
        id: "flame_blade",
        name: "Flame Blade",
        description: "A blade wreathed in magical fire. Chance to burn enemies.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 22,
        reach: 1.5,
        cooldown: 0.7,
        spread: 1.2,
        statusEffect: { type: 'burn', chance: 0.3, duration: 3.0 }
    },
    'mithril_greatsword': {
        id: "mithril_greatsword",
        name: "Mithril Greatsword",
        description: "A legendary greatsword forged from mithril.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: true,
        damage: 35,
        reach: 2,
        cooldown: 1,
        spread: 1.8
    },
    'sword_1': {
        id: "sword_1",
        name: "Steel Sword",
        description: "A standard issue broadsword. Reliable and balanced.",
        category: "WEAPON",
        twoHanded: false,
        damage: 10,
        reach: 1.2,
        cooldown: 0.6,
        spread: 0.8
    },
    'greatsword_1': {
        id: "greatsword_1",
        name: "Iron Greatsword",
        description: "A massive two-handed blade. Slow but devastating.",
        category: "WEAPON",
        twoHanded: true,
        damage: 25,
        reach: 1.8,
        cooldown: 1.2,
        spread: 1.5
    },
    'obsidian_sword': {
        id: "obsidian_sword",
        name: "Obsidian Greatsword",
        description: "A blade made of pure draconic obsidian. Extremely volatile.",
        category: "WEAPON",
        twoHanded: true,
        damage: 65,
        reach: 2.0,
        cooldown: 0.9,
        spread: 1.8
    },
    'kobold_dagger': {
        id: "kobold_dagger",
        name: "Kobold Dagger",
        description: "A small, jagged blade used by kobold workers.",
        category: "WEAPON",
        damage: 6,
        reach: 0.8,
        cooldown: 0.2,
        spread: 0.4
    },
    'kobold_spear': {
        id: "kobold_spear",
        name: "Kobold Spear",
        description: "A crude but effective spear used by kobold warriors.",
        category: "WEAPON",
        twoHanded: true,
        damage: 15,
        reach: 2.2,
        cooldown: 0.7,
        spread: 0.4
    },
    'shovel_1': {
        id: "shovel_1",
        name: "Iron Shovel",
        description: "A sturdy shovel. Can be used as a weapon or assigned to quick slots to dig.",
        category: "WEAPON",
        twoHanded: true,
        damage: 8,
        reach: 1.5,
        cooldown: 0.8,
        spread: 0.5
    },
    'pickaxe_1': {
        id: "pickaxe_1",
        name: "Iron Pickaxe",
        description: "A sturdy pickaxe. Can be used as a weapon or assigned to quick slots to mine downwards.",
        category: "WEAPON",
        twoHanded: true,
        damage: 12,
        reach: 1.5,
        cooldown: 0.9,
        spread: 0.5
    },
    'axe_1': {
        id: "axe_1",
        name: "Iron Axe",
        description: "A sharp axe. Can be used as a weapon or assigned to quick slots to chop down trees.",
        category: "WEAPON",
        twoHanded: true,
        damage: 15,
        reach: 1.5,
        cooldown: 1,
        spread: 0.5
    },
    'hoe_1': {
        id: "hoe_1",
        name: "Wooden Hoe",
        description: "A simple wooden hoe. Assign to quick slots to till dirt into soil.",
        category: "WEAPON",
        twoHanded: true,
        damage: 5,
        reach: 1.5,
        cooldown: 0.8,
        spread: 0.5
    },
    'shortbow_1': {
        id: "shortbow_1",
        name: "Wooden Shortbow",
        description: "A simple bow. Good for keeping enemies at a distance.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 8,
        cooldown: 0.8,
        projectileSpeed: 20
    },
    'iron_shortbow': {
        id: "iron_shortbow",
        name: "Iron Shortbow",
        description: "A sturdy bow reinforced with iron.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 15,
        cooldown: 0.7,
        projectileSpeed: 25
    },
    'elven_longbow': {
        id: "elven_longbow",
        name: "Elven Longbow",
        description: "A finely crafted bow of ancient wood. Hold attack for 1s to charge a Multi-Shot (Consumes 15 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 22,
        cooldown: 0.6,
        projectileSpeed: 30,
        secondaryAbility: "BOW_MULTI_SHOT",
        chargeTime: 1.0,
        chargeManaCost: 15
    },
    'dragon_bone_bow': {
        id: "dragon_bone_bow",
        name: "Dragon Bone Bow",
        description: "Carved from the bones of a drake. Hold attack for 1.5s to charge an Explosive Shot (Consumes 25 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: true,
        damage: 35,
        cooldown: 1.0,
        projectileSpeed: 35,
        secondaryAbility: "BOW_EXPLOSIVE_SHOT",
        chargeTime: 1.5,
        chargeManaCost: 25
    },
    'wooden_boomerang': {
        id: "wooden_boomerang",
        name: "Wooden Boomerang",
        description: "A curved piece of wood that returns when thrown. Equipping unlocks the Boomerang talent.",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 5,
        cooldown: 1,
        projectileSpeed: 12
    },
    'green_metal_boomerang': {
        id: "green_metal_boomerang",
        name: "Green Metal Boomerang",
        description: "A finely crafted boomerang. Hold attack to charge a Spread Shot (Consumes 15 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 15,
        cooldown: 0.8,
        projectileSpeed: 16,
        secondaryAbility: "BOOMERANG_SPREAD_SHOT",
        chargeTime: 1.0,
        chargeManaCost: 15
    },
    'red_metal_boomerang': {
        id: "red_metal_boomerang",
        name: "Red Metal Boomerang",
        description: "A heavy, seeking boomerang. Hold attack to charge a Seeking Shot (Consumes 20 Mana).",
        category: "WEAPON",
        type: "RANGED",
        twoHanded: false,
        damage: 25,
        cooldown: 0.8,
        projectileSpeed: 18,
        secondaryAbility: "BOOMERANG_SEEKER_SHOT",
        chargeTime: 1.0,
        chargeManaCost: 20
    },
    'staff_fire_ranged': {
        id: "staff_fire_ranged",
        name: "Staff of Firebolts",
        description: "A wooden staff topped with a glowing ruby. Shoots bolts of fire.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "FIRE",
        twoHanded: true,
        damage: 15,
        cooldown: 0.8,
        projectileSpeed: 12
    },
    'staff_ice_aoe': {
        id: "staff_ice_aoe",
        name: "Staff of Frost Nova",
        description: "An icy staff that unleashes a freezing blast around the caster.",
        category: "WEAPON",
        type: "MAGIC_AOE",
        damageType: "ICE",
        twoHanded: true,
        damage: 12,
        reach: 3.5,
        cooldown: 1.5
    },
    'staff_lightning_ranged': {
        id: "staff_lightning_ranged",
        name: "Staff of Sparks",
        description: "Crackles with electricity. Fires fast-moving lightning projectiles.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "LIGHTNING",
        twoHanded: true,
        damage: 10,
        cooldown: 0.5,
        projectileSpeed: 25
    },
    'staff_arcane_aoe': {
        id: "staff_arcane_aoe",
        name: "Staff of Arcane Burst",
        description: "Releases a wave of pure arcane energy in a wide area.",
        category: "WEAPON",
        type: "MAGIC_AOE",
        damageType: "ARCANE",
        twoHanded: true,
        damage: 20,
        reach: 4,
        cooldown: 2
    },
    'staff_inferno': {
        id: "staff_inferno",
        name: "Staff of the Inferno",
        description: "Channels intense flames. Hold attack to call down a meteor.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "FIRE",
        twoHanded: true,
        damage: 25,
        cooldown: 1,
        projectileSpeed: 10,
        spellId: "fire_bolt",
        manaCost: 5,
        secondaryAbility: "METEOR",
        chargeTime: 2,
        chargeManaCost: 40
    },
    'staff_necromancer': {
        id: "staff_necromancer",
        name: "Necromancer's Crook",
        description: "A twisted staff of bone. Hold attack to summon a skeleton minion.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ACID",
        twoHanded: true,
        damage: 15,
        cooldown: 0.8,
        projectileSpeed: 12,
        spellId: "acid_bolt",
        manaCost: 5,
        secondaryAbility: "SUMMON_SKELETON",
        chargeTime: 2.5,
        chargeManaCost: 50
    },
    'staff_grove': {
        id: "staff_grove",
        name: "Staff of the Grove",
        description: "A living branch. Hold attack to root nearby enemies.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "PHYSICAL",
        twoHanded: true,
        damage: 12,
        cooldown: 0.6,
        projectileSpeed: 15,
        spellId: "arcane_bolt",
        manaCost: 4,
        secondaryAbility: "ROOT",
        chargeTime: 1.5,
        chargeManaCost: 25
    },
    'staff_heavens': {
        id: "staff_heavens",
        name: "Staff of the Heavens",
        description: "Crackles with energy. Hold attack for a lightning strike.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "LIGHTNING",
        twoHanded: true,
        damage: 20,
        cooldown: 0.9,
        projectileSpeed: 18,
        spellId: "lightning_bolt",
        manaCost: 6,
        secondaryAbility: "LIGHTNING_STRIKE",
        chargeTime: 2,
        chargeManaCost: 35
    },
    'staff_magma': {
        id: "staff_magma",
        name: "Magma Channeler",
        description: "Radiates heat. Hold attack to create a lava puddle at cursor.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "FIRE",
        twoHanded: true,
        damage: 18,
        cooldown: 1,
        projectileSpeed: 10,
        spellId: "fire_bolt",
        manaCost: 5,
        secondaryAbility: "LAVA_PUDDLE",
        chargeTime: 1.5,
        chargeManaCost: 20
    },
    'staff_glacial': {
        id: "staff_glacial",
        name: "Glacial Staff",
        description: "Freezing to the touch. Causes target to be slowed. Hold attack for Frost Nova.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ICE",
        twoHanded: true,
        damage: 16,
        cooldown: 0.8,
        projectileSpeed: 12,
        spellId: "ice_bolt",
        manaCost: 5,
        secondaryAbility: "FROST_NOVA",
        chargeTime: 2,
        chargeManaCost: 30,
        statusEffect: { type: 'chill', chance: 1.0, duration: 4.0 }
    },
    'staff_void': {
        id: "staff_void",
        name: "Void Staff",
        description: "Absorbs all light. Hold attack to conjure a Black Hole.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ARCANE",
        twoHanded: true,
        damage: 30,
        cooldown: 1.5,
        projectileSpeed: 8,
        spellId: "arcane_bolt",
        manaCost: 10,
        secondaryAbility: "BLACK_HOLE",
        chargeTime: 3,
        chargeManaCost: 60
    },
    'staff_druid': {
        id: "staff_druid",
        name: "Staff of the Druid",
        description: "Teems with life. Hold attack for Mass Heal.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ACID",
        twoHanded: true,
        damage: 10,
        cooldown: 0.5,
        projectileSpeed: 14,
        spellId: "acid_bolt",
        manaCost: 3,
        secondaryAbility: "MASS_HEAL",
        chargeTime: 2.5,
        chargeManaCost: 45
    },
    'staff_time': {
        id: "staff_time",
        name: "Time-Mender's Staff",
        description: "Distorts reality. Hold attack to stop time.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ARCANE",
        twoHanded: true,
        damage: 22,
        cooldown: 1.2,
        projectileSpeed: 20,
        spellId: "arcane_bolt",
        manaCost: 8,
        secondaryAbility: "TIME_STOP",
        chargeTime: 3,
        chargeManaCost: 80
    },
    'staff_wind': {
        id: "staff_wind",
        name: "Staff of the Wind",
        description: "Light as a feather. Hold attack to push enemies back.",
        category: "WEAPON",
        type: "MAGIC_RANGED",
        damageType: "ARCANE",
        twoHanded: true,
        damage: 14,
        cooldown: 0.7,
        projectileSpeed: 16,
        spellId: "arcane_bolt",
        manaCost: 4,
        secondaryAbility: "PUSH_BACK",
        chargeTime: 1,
        chargeManaCost: 15
    },
    'dark_elf_blade': {
        id: "dark_elf_blade",
        name: "Dark Elf Blade",
        description: "A wicked, curved blade favored by dark elves. Coated in strange poison.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: false,
        damage: 22,
        reach: 1.2,
        cooldown: 0.4,
        spread: 0.5,
        damageType: "ACID",
        statusEffect: { type: 'poison', chance: 0.5, duration: 5.0 }
    },
    'dark_elf_bow': {
        id: "dark_elf_bow",
        name: "Dark Elf Bow",
        description: "A shadowy bow that fires with lethal precision.",
        type: "RANGED",
        category: "WEAPON",
        damage: 25,
        reach: 22,
        cooldown: 0.5,
        ammoType: "ARROW",
        projectileSpeed: 20
    },
    'dwarven_hammer': {
        id: "dwarven_hammer",
        name: "Dwarven Warhammer",
        description: "A massive block of steel on a stick. Unbelievably heavy.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: true,
        damage: 40,
        reach: 1.6,
        cooldown: 1.2,
        spread: 1.0,
        damageType: "PHYSICAL"
    },
    'dwarven_pickaxe': {
        id: "dwarven_pickaxe",
        name: "Dwarven Pickaxe",
        description: "An incredibly sturdy tool. Cuts through stone like butter, and skull like thinner stone.",
        category: "WEAPON",
        type: "MELEE",
        twoHanded: true, // Typically high-tier pickaxes in this game are two-handed
        damage: 25,
        reach: 1.5,
        cooldown: 0.6,
        damageType: "DIG" // Essential for 5x block braking modifier
    },
    'gnomish_crossbow': {
        id: "gnomish_crossbow",
        name: "Gnomish Repeater Crossbow",
        description: "A complex mechanical marvel that fires bolts at extreme velocities.",
        type: "RANGED",
        category: "WEAPON",
        damage: 18,
        reach: 25,
        cooldown: 0.2, // Very fast fire rate
        ammoType: "ARROW",
        projectileSpeed: 30
    },
    'watering_can': {
        id: "watering_can",
        name: "Watering Can",
        description: "Waters dry tilled soil so crops grow.",
        damage: 1,
        reach: 1.5,
        cooldown: 0.5,
        spread: 0.2,
        category: "WEAPON",
        twoHanded: false,
        stackable: false,
        damageType: 'PHYSICAL'
    },
    'golden_shovel': {
        id: "golden_shovel",
        name: "Golden Shovel",
        description: "A very shiny shovel. Useful for gathering rare items, like honeycombs from Bee Hives.",
        damage: 15,
        reach: 1.5,
        cooldown: 0.6,
        spread: 0.2,
        category: "WEAPON",
        twoHanded: false,
        stackable: false,
        damageType: 'PHYSICAL'
    },
    
    // THERA WEAPONS
    'bone_club': {
        id: "bone_club",
        name: "Giant Bone Club",
        description: "A massively heavy club carved from a dinosaur femur.",
        category: "WEAPON",
        twoHanded: true,
        damage: 45,
        reach: 2.5,
        cooldown: 1.5, // Slow but devastating
        spread: 1.2
    },
    'raptor_sickle': {
        id: "raptor_sickle",
        name: "Raptor Sickle",
        description: "A fast, slashing weapon crafted from raptor claws. Causes bleeding.",
        category: "WEAPON",
        twoHanded: false,
        damage: 22,
        reach: 1.0,
        cooldown: 0.3, // Extremely fast
        spread: 0.5,
        statusEffect: { type: 'bleed', chance: 0.3, duration: 4.0 }
    },
    'fossil_pickaxe': {
        id: "fossil_pickaxe",
        name: "Fossil Pickaxe",
        description: "A pickaxe made of fossilized bone and amber. Extracts fossils easily.",
        category: "WEAPON",
        twoHanded: true,
        damage: 25,
        reach: 1.5,
        cooldown: 0.6,
        spread: 0.5
    },
    'troll_tusk_sword': {
        id: "troll_tusk_sword",
        name: "Troll Tusk Sword",
        description: "A brutal, curved blade carved from a cave troll's tusk.",
        category: "WEAPON",
        twoHanded: false,
        damage: 38,
        reach: 1.8,
        cooldown: 0.8,
        spread: 0.7
    },
    'ogre_club': {
        id: "ogre_club",
        name: "Ogre Splinter Club",
        description: "A massive, crude club that deals devastating damage slowly.",
        category: "WEAPON",
        twoHanded: true,
        damage: 55,
        reach: 2.2,
        cooldown: 1.5,
        spread: 1.0
    }
};
