import type { Spell } from '../../registries/ItemRegistry';

export const ARCANE_SPELLS: Record<string, Spell> = {
  'shadow_flare': {
        id: 'shadow_flare',
        name: 'Shadow Flare',
        description: 'Shoots a dark arcane flare.',
        manaCost: 15,
        cooldown: 2.0,
        castTime: 0.4,
        damage: 50,
        reach: 20,
        spread: 0,
        projectileSpeed: 15,
        damageType: 'ARCANE',
        type: 'PROJECTILE' 
    },
  'magic_block': {
        id: "magic_block",
        name: "Magic Block",
        description: "Create a temporary block.",
        manaCost: 10,
        cooldown: 5,
        damage: 0,
        reach: 3,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'arcane_light': {
        id: "arcane_light",
        name: "Arcane Light",
        description: "Create a magical light that follows you.",
        manaCost: 15,
        cooldown: 10,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'arcane_bolt': {
        id: "arcane_bolt",
        name: "Arcane Bolt",
        description: "Hurl a bolt of pure arcane energy.",
        manaCost: 8,
        cooldown: 0.5,
        damage: 12,
        reach: 5,
        spread: 0,
        damageType: "ARCANE",
        type: "PROJECTILE",
        projectileSpeed: 18,
        stackable: true,
        maxStack: 99
    },
  'arcane_ball': {
        id: "arcane_ball",
        name: "Arcane Ball",
        description: "Unleash a burst of arcane energy around you.",
        manaCost: 20,
        cooldown: 1.5,
        damage: 15,
        reach: 6,
        spread: 0,
        damageType: "ARCANE",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
  'rune_of_arcane': {
        id: "rune_of_arcane",
        name: "Rune of Arcane",
        description: "A chaotic rune that detonates with raw, unfiltered arcane magic.",
        manaCost: 45,
        cooldown: 10.0,
        damage: 150,
        reach: 8,
        spread: 0,
        damageType: "ARCANE",
        type: "AOE",
        castTime: 1.2,
        stackable: true,
        maxStack: 99
    },
};
