import type { Spell } from '../../registries/ItemRegistry';

export const COMBAT_SPELLS: Record<string, Spell> = {
  'venom_cloud': {
        id: 'venom_cloud',
        name: 'Venom Cloud',
        description: 'Releases a toxic cloud of acid around you.',
        manaCost: 30,
        cooldown: 8.0,
        castTime: 1.0,
        damage: 30,
        reach: 6,
        spread: 0,
        damageType: 'ACID',
        statusEffect: { type: 'poison', chance: 1.0, duration: 12.0 },
        type: 'AOE'
    },
  'divine_smite': {
        id: 'divine_smite',
        name: 'Divine Smite',
        description: 'Fires a powerful blast of holy magic.',
        manaCost: 25,
        cooldown: 4.0,
        castTime: 0.8,
        damage: 100,
        reach: 25,
        spread: 0,
        projectileSpeed: 25,
        damageType: 'MAGIC',
        type: 'PROJECTILE' 
    },
  'carrot_bloom': {
        id: 'carrot_bloom',
        name: 'Carrot Bloom',
        description: 'Creates carrots all around you.',
        manaCost: 20,
        cooldown: 5.0,
        castTime: 3.0,
        damage: 0,
        reach: 4,
        spread: 0,
        damageType: 'CARROT_BLOOM' as any,
        type: 'AOE'
    },
  'grapple_shot_spell': {
        id: "grapple_shot_spell",
        name: "Grapple Shot",
        description: "Fires a grappling hook that pulls you toward solid blocks.",
        manaCost: 10,
        cooldown: 1.0,
        damage: 5,
        reach: 40,
        spread: 0.1,
        damageType: "GRAPPLE",
        projectileSpeed: 30,
        type: "PROJECTILE"
    },
  'levitate': {
        id: "levitate",
        name: "Levitate",
        description: "Float above traps and liquids for 10 seconds.",
        manaCost: 20,
        cooldown: 15,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'speed': {
        id: "speed",
        name: "Speed",
        description: "Move 50% faster for 10 seconds.",
        manaCost: 15,
        cooldown: 15,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'invisibility': {
        id: "invisibility",
        name: "Invisibility",
        description: "Become invisible for a short duration.",
        manaCost: 30,
        cooldown: 30,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'fear': {
        id: "fear",
        name: "Fear",
        description: "Cause nearby enemies to flee in terror.",
        manaCost: 25,
        cooldown: 20,
        damage: 0,
        reach: 8,
        spread: 0,
        damageType: "MAGIC",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
  'exploding_rune': {
        id: "exploding_rune",
        name: "Exploding Rune",
        description: "Place a rune that explodes when enemies are near.",
        manaCost: 30,
        cooldown: 15,
        damage: 150,
        reach: 1.5,
        spread: 0,
        damageType: "FIRE",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'mark': {
        id: "mark",
        name: "Mark",
        description: "Places a magical mark at your current location.",
        manaCost: 10,
        cooldown: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        castTime: 1,
        stackable: true,
        maxStack: 99
    },
  'return': {
        id: "return",
        name: "Return",
        description: "Teleports you to your mark.",
        manaCost: 20,
        cooldown: 5,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        castTime: 2,
        stackable: true,
        maxStack: 99
    },
  'burning_hands': {
        id: "burning_hands",
        name: "Burning Hands",
        description: "Unleash a short burst of fire directly in front of you.",
        manaCost: 20,
        cooldown: 1.5,
        damage: 25,
        reach: 3,
        spread: 0.7853981633974483,
        damageType: "FIRE",
        type: "CONE",
        statusEffect: { type: "burn", duration: 5.0, chance: 1.0 },
        stackable: true,
        maxStack: 99
    },
  'force_bolt': {
        id: "force_bolt",
        name: "Force Bolt",
        description: "Hurl a bolt of physical force.",
        manaCost: 10,
        cooldown: 1,
        damage: 15,
        reach: 5,
        spread: 0,
        damageType: "PHYSICAL",
        type: "PROJECTILE",
        projectileSpeed: 15,
        stackable: true,
        maxStack: 99
    },
  'force_ball': {
        id: "force_ball",
        name: "Force Ball",
        description: "Unleash a burst of physical force around you.",
        manaCost: 25,
        cooldown: 2,
        damage: 20,
        reach: 4,
        spread: 0,
        damageType: "PHYSICAL",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
  'portal_red': {
        id: "portal_red",
        name: "Red Portal",
        description: "Place a red portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
  'portal_blue': {
        id: "portal_blue",
        name: "Blue Portal",
        description: "Place a blue portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
  'portal_yellow': {
        id: "portal_yellow",
        name: "Yellow Portal",
        description: "Place a yellow portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
  'portal_green': {
        id: "portal_green",
        name: "Green Portal",
        description: "Place a green portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
  'portal_purple': {
        id: "portal_purple",
        name: "Purple Portal",
        description: "Place a purple portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
  'portal_orange': {
        id: "portal_orange",
        name: "Orange Portal",
        description: "Place an orange portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
  'dig_bolt': {
        id: "dig_bolt",
        name: "Dig Bolt",
        description: "Hurl a bolt of arcane energy that instantly destroys the block it hits.",
        manaCost: 5,
        cooldown: 0.5,
        damage: 0,
        reach: 5,
        spread: 0,
        damageType: "DIG",
        type: "PROJECTILE",
        projectileSpeed: 20,
        stackable: true,
        maxStack: 99
    },
  'black_hole': {
        id: "black_hole",
        name: "Black Hole",
        description: "Creates a damage void that sucks in opponents.",
        manaCost: 40,
        cooldown: 8.0,
        damage: 25,
        reach: 10,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'vampiric_bolt': {
        id: "vampiric_bolt",
        name: "Vampiric Bolt",
        description: "Hurls a bolt of blood magic that leeches life.",
        manaCost: 15,
        cooldown: 1.0,
        damage: 20,
        reach: 6,
        spread: 0,
        damageType: "VAMPIRIC",
        type: "PROJECTILE",
        projectileSpeed: 15,
        stackable: true,
        maxStack: 99
    },
  'vampiric_ball': {
        id: "vampiric_ball",
        name: "Vampiric Ball",
        description: "Unleash a burst of life-stealing magic around you.",
        manaCost: 30,
        cooldown: 3.0,
        damage: 30,
        reach: 4,
        spread: 0,
        damageType: "VAMPIRIC",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
  'mist_form': {
        id: "mist_form",
        name: "Mist Form",
        description: "Temporarily become a mist cloud. Invulnerable, unable to attack. Hold jump to lift upward.",
        manaCost: 25,
        cooldown: 15.0,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'eye': {
        id: "eye",
        name: "Eye",
        description: "Hold to conjure a floating eye. Move around as the eye, release to return.",
        manaCost: 10,
        cooldown: 1.0,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'meteor_shower': {
        id: "meteor_shower",
        name: "Meteor Shower",
        description: "Call down devastating meteors from the sky to incinerate a huge area around you.",
        manaCost: 40,
        cooldown: 15.0,
        damage: 200,
        reach: 12,
        spread: Math.PI * 2,
        damageType: "FIRE",
        type: "AOE",
        castTime: 3.0,
        stackable: true,
        maxStack: 99
    },
  'rune_of_destruction': {
        id: "rune_of_destruction",
        name: "Rune of Destruction",
        description: "Binds destructive energy into a massive arcane blast, obliterating anything nearby.",
        manaCost: 45,
        cooldown: 8.0,
        damage: 180,
        reach: 8,
        spread: 0,
        damageType: "ARCANE",
        type: "AOE",
        castTime: 1.5,
        stackable: true,
        maxStack: 99
    },
  'rune_of_gravity': {
        id: "rune_of_gravity",
        name: "Rune of Gravity",
        description: "Places a crushing gravity rune that deals heavy damage and binds enemies in space.",
        manaCost: 30,
        cooldown: 12.0,
        damage: 120,
        reach: 6,
        spread: 0,
        damageType: "MAGIC",
        type: "AOE",
        castTime: 1.0,
        stackable: true,
        maxStack: 99
    },
  'rune_of_life': {
        id: "rune_of_life",
        name: "Rune of Life",
        description: "Invoke an ancient rune that bathes the caster in immense healing energy.",
        manaCost: 50,
        cooldown: 20.0,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        castTime: 2.0,
        stackable: true,
        maxStack: 99
    },
};
