import type { Spell } from '../../registries/ItemRegistry';

export const HOLY_SPELLS: Record<string, Spell> = {
  'heal': {
        id: "heal",
        name: "Heal",
        description: "Restore 25 health.",
        manaCost: 20,
        cooldown: 5,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'major_heal': {
        id: "major_heal",
        name: "Major Heal",
        description: "Restore 60 health.",
        manaCost: 40,
        cooldown: 10,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'lightning_bolt': {
        id: "lightning_bolt",
        name: "Lightning Bolt",
        description: "Hurl a bolt of lightning at your enemies.",
        manaCost: 15,
        cooldown: 1,
        damage: 20,
        reach: 5,
        spread: 0,
        damageType: "LIGHTNING",
        type: "PROJECTILE",
        projectileSpeed: 20,
        stackable: true,
        maxStack: 99
    },
  'lightning_ball': {
        id: "lightning_ball",
        name: "Lightning Ball",
        description: "Unleash a burst of lightning around you.",
        manaCost: 30,
        cooldown: 2.5,
        damage: 25,
        reach: 5,
        spread: 0,
        damageType: "LIGHTNING",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
  'chain_lightning': {
        id: "chain_lightning",
        name: "Chain Lightning",
        description: "Arcs a bolt of lightning between multiple targets.",
        manaCost: 35,
        cooldown: 3.0,
        damage: 40,
        reach: 12,
        spread: 0,
        damageType: "LIGHTNING",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'rune_of_lightning': {
        id: "rune_of_lightning",
        name: "Rune of Lightning",
        description: "A pulsating rune that discharges violent electrical energy.",
        manaCost: 40,
        cooldown: 12.0,
        damage: 160,
        reach: 6,
        spread: 0,
        damageType: "LIGHTNING",
        type: "AOE",
        castTime: 1.2,
        stackable: true,
        maxStack: 99
    },
  'rune_of_holy': {
        id: "rune_of_holy",
        name: "Rune of Holy",
        description: "A divine rune that scorches enemies with cleansing light.",
        manaCost: 40,
        cooldown: 12.0,
        damage: 140,
        reach: 7,
        spread: 0,
        damageType: "MAGIC",
        type: "AOE",
        castTime: 1.5,
        stackable: true,
        maxStack: 99
    },
};
