import type { Spell } from '../../registries/ItemRegistry';

export const ICE_SPELLS: Record<string, Spell> = {
  'blizzard': {
        id: 'blizzard',
        name: 'Blizzard',
        description: 'Creates a freezing storm that chills all nearby enemies.',
        manaCost: 35,
        cooldown: 8.0,
        castTime: 1.0,
        damage: 40,
        reach: 8,
        spread: 0,
        damageType: 'ICE',
        statusEffect: { type: 'chill', chance: 1.0, duration: 8.0 },
        type: 'AOE'
    },
  'frost_vortice': {
        id: 'frost_vortice',
        name: 'Frost Vortice',
        description: 'Summons a slow moving frost twister.',
        manaCost: 15,
        cooldown: 6.0,
        castTime: 0.5,
        damage: 15,
        reach: 1,
        spread: 0,
        damageType: 'ICE',
        statusEffect: { type: 'chill', chance: 1.0, duration: 4.0 },
        type: 'PROJECTILE'
    },
  'acid_vortice': {
        id: 'acid_vortice',
        name: 'Acid Vortice',
        description: 'Summons a slow moving acid twister.',
        manaCost: 15,
        cooldown: 6.0,
        castTime: 0.5,
        damage: 15,
        reach: 1,
        spread: 0,
        damageType: 'ACID',
        statusEffect: { type: 'poison', chance: 1.0, duration: 4.0 },
        type: 'PROJECTILE'
    },
  'ice_bolt': {
        id: "ice_bolt",
        name: "Ice Bolt",
        description: "Hurl a bolt of ice at your enemies.",
        manaCost: 10,
        cooldown: 0.8,
        damage: 15,
        reach: 5,
        spread: 0,
        damageType: "ICE",
        type: "PROJECTILE",
        projectileSpeed: 15,
        statusEffect: { type: "chill", duration: 5.0, chance: 0.5 },
        stackable: true,
        maxStack: 99
    },
  'ice_ball': {
        id: "ice_ball",
        name: "Ice Ball",
        description: "Unleash a burst of ice around you.",
        manaCost: 25,
        cooldown: 2,
        damage: 20,
        reach: 4,
        spread: 0,
        damageType: "ICE",
        type: "AOE",
        statusEffect: { type: "chill", duration: 5.0, chance: 1.0 },
        stackable: true,
        maxStack: 99
    },
  'rune_of_ice': {
        id: "rune_of_ice",
        name: "Rune of Ice",
        description: "A freezing rune that detonates, causing extreme cold and chill.",
        manaCost: 35,
        cooldown: 10.0,
        damage: 130,
        reach: 6,
        spread: 0,
        damageType: "ICE",
        statusEffect: { type: "chill", duration: 8.0, chance: 1.0 },
        type: "AOE",
        castTime: 1.2,
        stackable: true,
        maxStack: 99
    },
};
