import type { Spell } from '../../registries/ItemRegistry';

export const ALL_SPELLS: Record<string, Spell> = {
    'grapple_shot_spell': {
        id: "grapple_shot_spell",
        name: "Grapple Shot",
        description: "Fires a grappling hook that pulls you toward solid blocks.",
        manaCost: 10,
        cooldown: 1.0,
        damage: 5,
        reach: 40,
        spread: 0.1,
        damageType: "GRAPPLE",
        projectileSpeed: 30,
        type: "PROJECTILE"
    },
    'blink': {
        id: "blink",
        name: "Blink",
        description: "Teleport a short distance forward.",
        manaCost: 15,
        cooldown: 3,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'levitate': {
        id: "levitate",
        name: "Levitate",
        description: "Float above traps and liquids for 10 seconds.",
        manaCost: 20,
        cooldown: 15,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'speed': {
        id: "speed",
        name: "Speed",
        description: "Move 50% faster for 10 seconds.",
        manaCost: 15,
        cooldown: 15,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'heal': {
        id: "heal",
        name: "Heal",
        description: "Restore 25 health.",
        manaCost: 20,
        cooldown: 5,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'major_heal': {
        id: "major_heal",
        name: "Major Heal",
        description: "Restore 60 health.",
        manaCost: 40,
        cooldown: 10,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'summon_wolf': {
        id: "summon_wolf",
        name: "Summon Wolf",
        description: "Summon a friendly wolf to fight for you.",
        manaCost: 30,
        cooldown: 30,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'summon_bear': {
        id: "summon_bear",
        name: "Summon Bear",
        description: "Summon a friendly bear to fight for you.",
        manaCost: 50,
        cooldown: 45,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'magic_block': {
        id: "magic_block",
        name: "Magic Block",
        description: "Create a temporary block.",
        manaCost: 10,
        cooldown: 5,
        damage: 0,
        reach: 3,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'invisibility': {
        id: "invisibility",
        name: "Invisibility",
        description: "Become invisible for a short duration.",
        manaCost: 30,
        cooldown: 30,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'fear': {
        id: "fear",
        name: "Fear",
        description: "Cause nearby enemies to flee in terror.",
        manaCost: 25,
        cooldown: 20,
        damage: 0,
        reach: 8,
        spread: 0,
        damageType: "MAGIC",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
    'arcane_light': {
        id: "arcane_light",
        name: "Arcane Light",
        description: "Create a magical light that follows you.",
        manaCost: 15,
        cooldown: 10,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'exploding_rune': {
        id: "exploding_rune",
        name: "Exploding Rune",
        description: "Place a rune that explodes when enemies are near.",
        manaCost: 30,
        cooldown: 15,
        damage: 150,
        reach: 1.5,
        spread: 0,
        damageType: "FIRE",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'summon_wyrmling': {
        id: "summon_wyrmling",
        name: "Summon Wyrmling",
        description: "Summon a powerful Wyrmling to fight for you.",
        manaCost: 80,
        cooldown: 60,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'summon_skeleton': {
        id: "summon_skeleton",
        name: "Summon Skeleton",
        description: "Summon a skeleton to fight for you.",
        manaCost: 25,
        cooldown: 20,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'summon_zombie': {
        id: "summon_zombie",
        name: "Summon Zombie",
        description: "Summon a resilient zombie to fight for you.",
        manaCost: 35,
        cooldown: 25,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'summon_bone_pile': {
        id: "summon_bone_pile",
        name: "Summon Bone Pile",
        description: "Create a bone pile that spawns skeletons.",
        manaCost: 60,
        cooldown: 45,
        damage: 0,
        reach: 5,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
    'animate_stone': {
        id: "animate_stone",
        name: "Animate Stone",
        description: "Turn a stone block into a Stone Golem.",
        manaCost: 40,
        cooldown: 20,
        damage: 0,
        reach: 8,
        spread: 0,
        damageType: "ANIMATE_STONE",
        type: "PROJECTILE",
        projectileSpeed: 15,
        stackable: true,
        maxStack: 99
    },
    'mark': {
        id: "mark",
        name: "Mark",
        description: "Places a magical mark at your current location.",
        manaCost: 10,
        cooldown: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        castTime: 1,
        stackable: true,
        maxStack: 99
    },
    'return': {
        id: "return",
        name: "Return",
        description: "Teleports you to your mark.",
        manaCost: 20,
        cooldown: 5,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        castTime: 2,
        stackable: true,
        maxStack: 99
    },
    'burning_hands': {
        id: "burning_hands",
        name: "Burning Hands",
        description: "Unleash a short burst of fire directly in front of you.",
        manaCost: 20,
        cooldown: 1.5,
        damage: 25,
        reach: 3,
        spread: 0.7853981633974483,
        damageType: "FIRE",
        type: "CONE",
        statusEffect: { type: "burn", duration: 5.0, chance: 1.0 },
        stackable: true,
        maxStack: 99
    },
    'fire_bolt': {
        id: "fire_bolt",
        name: "Fire Bolt",
        description: "Hurl a bolt of fire at your enemies.",
        manaCost: 10,
        cooldown: 0.8,
        damage: 15,
        reach: 5,
        spread: 0,
        damageType: "FIRE",
        type: "PROJECTILE",
        projectileSpeed: 15,
        statusEffect: { type: "burn", duration: 5.0, chance: 0.5 },
        stackable: true,
        maxStack: 99
    },
    'ice_bolt': {
        id: "ice_bolt",
        name: "Ice Bolt",
        description: "Hurl a bolt of ice at your enemies.",
        manaCost: 10,
        cooldown: 0.8,
        damage: 15,
        reach: 5,
        spread: 0,
        damageType: "ICE",
        type: "PROJECTILE",
        projectileSpeed: 15,
        statusEffect: { type: "chill", duration: 5.0, chance: 0.5 },
        stackable: true,
        maxStack: 99
    },
    'lightning_bolt': {
        id: "lightning_bolt",
        name: "Lightning Bolt",
        description: "Hurl a bolt of lightning at your enemies.",
        manaCost: 15,
        cooldown: 1,
        damage: 20,
        reach: 5,
        spread: 0,
        damageType: "LIGHTNING",
        type: "PROJECTILE",
        projectileSpeed: 20,
        stackable: true,
        maxStack: 99
    },
    'arcane_bolt': {
        id: "arcane_bolt",
        name: "Arcane Bolt",
        description: "Hurl a bolt of pure arcane energy.",
        manaCost: 8,
        cooldown: 0.5,
        damage: 12,
        reach: 5,
        spread: 0,
        damageType: "ARCANE",
        type: "PROJECTILE",
        projectileSpeed: 18,
        stackable: true,
        maxStack: 99
    },
    'acid_bolt': {
        id: "acid_bolt",
        name: "Acid Bolt",
        description: "Hurl a corrosive bolt of acid.",
        manaCost: 12,
        cooldown: 1.2,
        damage: 18,
        reach: 5,
        spread: 0,
        damageType: "ACID",
        type: "PROJECTILE",
        projectileSpeed: 12,
        statusEffect: { type: "poison", duration: 5.0, chance: 0.5 },
        stackable: true,
        maxStack: 99
    },
    'force_bolt': {
        id: "force_bolt",
        name: "Force Bolt",
        description: "Hurl a bolt of physical force.",
        manaCost: 10,
        cooldown: 1,
        damage: 15,
        reach: 5,
        spread: 0,
        damageType: "PHYSICAL",
        type: "PROJECTILE",
        projectileSpeed: 15,
        stackable: true,
        maxStack: 99
    },
    'fire_ball': {
        id: "fire_ball",
        name: "Fire Ball",
        description: "Unleash a burst of fire around you.",
        manaCost: 25,
        cooldown: 2,
        damage: 20,
        reach: 4,
        spread: 0,
        damageType: "FIRE",
        type: "AOE",
        statusEffect: { type: "burn", duration: 5.0, chance: 1.0 },
        stackable: true,
        maxStack: 99
    },
    'ice_ball': {
        id: "ice_ball",
        name: "Ice Ball",
        description: "Unleash a burst of ice around you.",
        manaCost: 25,
        cooldown: 2,
        damage: 20,
        reach: 4,
        spread: 0,
        damageType: "ICE",
        type: "AOE",
        statusEffect: { type: "chill", duration: 5.0, chance: 1.0 },
        stackable: true,
        maxStack: 99
    },
    'lightning_ball': {
        id: "lightning_ball",
        name: "Lightning Ball",
        description: "Unleash a burst of lightning around you.",
        manaCost: 30,
        cooldown: 2.5,
        damage: 25,
        reach: 5,
        spread: 0,
        damageType: "LIGHTNING",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
    'arcane_ball': {
        id: "arcane_ball",
        name: "Arcane Ball",
        description: "Unleash a burst of arcane energy around you.",
        manaCost: 20,
        cooldown: 1.5,
        damage: 15,
        reach: 6,
        spread: 0,
        damageType: "ARCANE",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
    'acid_ball': {
        id: "acid_ball",
        name: "Acid Ball",
        description: "Unleash a burst of corrosive acid around you.",
        manaCost: 25,
        cooldown: 2,
        damage: 22,
        reach: 3.5,
        spread: 0,
        damageType: "ACID",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
    'force_ball': {
        id: "force_ball",
        name: "Force Ball",
        description: "Unleash a burst of physical force around you.",
        manaCost: 25,
        cooldown: 2,
        damage: 20,
        reach: 4,
        spread: 0,
        damageType: "PHYSICAL",
        type: "AOE",
        stackable: true,
        maxStack: 99
    },
    'portal_red': {
        id: "portal_red",
        name: "Red Portal",
        description: "Place a red portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
    'portal_blue': {
        id: "portal_blue",
        name: "Blue Portal",
        description: "Place a blue portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
    'portal_yellow': {
        id: "portal_yellow",
        name: "Yellow Portal",
        description: "Place a yellow portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
    'portal_green': {
        id: "portal_green",
        name: "Green Portal",
        description: "Place a green portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
    'portal_purple': {
        id: "portal_purple",
        name: "Purple Portal",
        description: "Place a purple portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
    'portal_orange': {
        id: "portal_orange",
        name: "Orange Portal",
        description: "Place an orange portal.",
        manaCost: 20,
        cooldown: 5,
        type: "UTILITY",
        castTime: 2,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
    'summon_rat': {
        id: "summon_rat",
        name: "Summon Rat",
        description: "Summons a loyal rat to fight for you.",
        manaCost: 15,
        cooldown: 10,
        type: "UTILITY",
        castTime: 1,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
    'dig_bolt': {
        id: "dig_bolt",
        name: "Dig Bolt",
        description: "Hurl a bolt of arcane energy that instantly destroys the block it hits.",
        manaCost: 5,
        cooldown: 0.5,
        damage: 0,
        reach: 5,
        spread: 0,
        damageType: "DIG",
        type: "PROJECTILE",
        projectileSpeed: 20,
        stackable: true,
        maxStack: 99
    },
    'meteor_shower': {
        id: "meteor_shower",
        name: "Meteor Shower",
        description: "Call down devastating meteors from the sky to incinerate a huge area around you.",
        manaCost: 40,
        cooldown: 15.0,
        damage: 200,
        reach: 12,
        spread: Math.PI * 2,
        damageType: "FIRE",
        type: "AOE",
        castTime: 3.0,
        stackable: true,
        maxStack: 99
    }
};
