import type { Spell } from '../../registries/ItemRegistry';

export const UTILITY_SPELLS: Record<string, Spell> = {
  'blink': {
        id: "blink",
        name: "Blink",
        description: "Teleport a short distance forward.",
        manaCost: 15,
        cooldown: 3,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'summon_wolf': {
        id: "summon_wolf",
        name: "Summon Wolf",
        description: "Summon a friendly wolf to fight for you.",
        manaCost: 30,
        cooldown: 30,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'summon_bear': {
        id: "summon_bear",
        name: "Summon Bear",
        description: "Summon a friendly bear to fight for you.",
        manaCost: 50,
        cooldown: 45,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'summon_wyrmling': {
        id: "summon_wyrmling",
        name: "Summon Wyrmling",
        description: "Summon a powerful Wyrmling to fight for you.",
        manaCost: 80,
        cooldown: 60,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'summon_skeleton': {
        id: "summon_skeleton",
        name: "Summon Skeleton",
        description: "Summon a skeleton to fight for you.",
        manaCost: 25,
        cooldown: 20,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'summon_zombie': {
        id: "summon_zombie",
        name: "Summon Zombie",
        description: "Summon a resilient zombie to fight for you.",
        manaCost: 35,
        cooldown: 25,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'summon_bone_pile': {
        id: "summon_bone_pile",
        name: "Summon Bone Pile",
        description: "Create a bone pile that spawns skeletons.",
        manaCost: 60,
        cooldown: 45,
        damage: 0,
        reach: 5,
        spread: 0,
        damageType: "MAGIC",
        type: "UTILITY",
        stackable: true,
        maxStack: 99
    },
  'summon_rat': {
        id: "summon_rat",
        name: "Summon Rat",
        description: "Summons a loyal rat to fight for you.",
        manaCost: 15,
        cooldown: 10,
        type: "UTILITY",
        castTime: 1,
        damage: 0,
        reach: 0,
        spread: 0,
        damageType: "MAGIC",
        stackable: true,
        maxStack: 99
    },
};
